/*
  ______         _____ _______   ____          ________ ____  
 |___  /   /\   |  __ \_   _\ \ / /\ \        / /  ____|  _ \ 
    / /   /  \  | |__) || |  \ V /  \ \  /\  / /| |__  | |_) |
   / /   / /\ \ |  ___/ | |   > <    \ \/  \/ / |  __| |  _ < 
  / /__ / ____ \| |    _| |_ / . \    \  /\  /  | |____| |_) |
 /_____/_/    \_\_|   |_____/_/ \_\    \/  \/   |______|____/ 
				                      ZAPiX Web
W H A T S A P P W E B   E X T R A C T O R						

ZAPiXWEB WhatsApp Extractor - 4 CHROME, FIREFOX, EDGE, OPERA 
(It also works offline for Browser extractions)

Script Name: SPIZAPIXWEB.js
Version: 2.3
Revised Date: 05/09/25

Description: A script that extracts throught Whatsapp WEB data records.
Technique described in paper:
Soares, A. (2022). WhatsApp Web Client Live Forensics Technique. In Proceedings of the 8th International Conference on Information Systems Security and Privacy - ICISSP, ISBN 978-989-758-553-1, pages 629-636. DOI: 10.5220/0011006400003120

Copyright: 2021 Alberto Magno <alberto.magno@gmail.com> 
URL: https://github.com/kraftdenker/cellebrite-UFEDPA-scripts

Manual: Copy and paste all this code into browser console + ENTER. 
Follow the commands in console window.
In Firefox, you have to manually type "allow paste" into the console to enable pasting.

---> (FOLLOWING INSTRUCTIONS FOR DESKTOP TECHNIQUE IS NOW DEPRECATED - META CHANGED DESKTOP RUNTIME TO DOTNET APP) 
WhatsApp Desktop  - Electron (For this whatsapp version, it only works online): 
-----------------------------------------------------------------

- ChangeLog -
v1 		- [05-18-21]: Wrote original code
v1.2	- [09-27-21]: Command to extract one or more chats.
v1.3	- [10-08-21]: Correct chat extraction
v1.4	- [12-03-21]: Change extraction to full support multiple devices
v1.5	- [02-21-22]: Hash, new decryption code (using vendor module ligsignal)
v1.5.1	- [08-31-22]: Adjust in which DOM element to grab the current chat name
v1.6	- [08-31-22]: Adaptation for use with Electron (Whatsapp Desktop App)
v1.7	- [01-04-23]: Adaption to new quotedMsg structure.
v1.8	- [03-01-23]: Adjust grabbing the current chat name
v1.9	- [07-26-23]: Adjust grabbing the current user account id.
v1.10	- [02-29-24]: function ZAPiX._internal_getChatByName getting chatname also using new field 'formattedTitle'
v2.0	- [06-23-24]: Code adaptions to new secutiry directives enabled by Meta. All included libraries no more need. All code using only meta dependencies. 
v2.1	- [08-01-24]: Function to clean chatnames with htmlcode(emojis) to be used by getchatbyname process (Add current chat option).
v.2.2 - [04-04-25]: Change in saveFile function to pure JS code (cutting dependecy with FileAPI) for compatibility issues with firefox and Safari
v.2.3 - [09-05-25]: update UserData function to get PhoneNumber 
Author: alberto.magno@gmail.com (https://github.com/kraftdenker)  _
*/

//-------------------------------
//ZAPIX INCLUDE
//-------------------------------
window.ZAPiX = {};
window._ZAPiX = {};

window.ZAPiX._serializeRawObj = (obj) => {
    if (obj && obj.toJSON) {
        return obj.toJSON();
    }
    return {}
};

window.ZAPiX._lastDigest = undefined;
window.ZAPiX._statusTextnode = undefined;
window.ZAPiX._zip = undefined;
window.ZAPiX._injectedStatusNode = undefined;
window.ZAPiX._injectedHeaderNode = undefined;
// --- Tables
window.ZAPiX._decodeZapMedia = {
    "image": "WhatsApp Image Keys",
    "sticker": "WhatsApp Image Keys",
    "video": "WhatsApp Video Keys",
    "audio": "WhatsApp Audio Keys",
    "document": "WhatsApp Document Keys",
    "image/webp": "WhatsApp Image Keys",
    "image/jpeg": "WhatsApp Image Keys",
    "image/png": "WhatsApp Image Keys",
    "video/mp4": "WhatsApp Video Keys",
    "audio/aac": "WhatsApp Audio Keys",
    "audio/ogg": "WhatsApp Audio Keys",
    "audio/wav": "WhatsApp Audio Keys",
	"ptt": "WhatsApp Audio Keys"
}

window.ZAPiX._mediaTypes = new Set();

window.ZAPiX._fileExtensions = JSON.parse('{"audio/aac": ".aac","application/x-abiword": ".abw","application/octet-stream": ".abw","video/x-msvideo": ".avi","application/vnd.amazon.ebook": ".azw","application/octet-stream": ".bin","image/bmp": ".bmp","application/x-bzip": ".bz","application/x-bzip2":".bz2","application/x-csh": ".csh","text/css": ".css","text/csv": ".csv","application/msword": ".doc","application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx","application/vnd.ms-fontobject": ".eot","application/epub+zip": ".epub","video/x-flv": ".flv","image/gif": ".gif","text/html": ".htm","text/html": ".html","image/x-icon": ".ico","text/calendar": ".ics","application/java-archive": ".jar","image/jpeg": ".jpeg","text/javascript": ".js","application/json": ".json","audio/midi": ".midi","audio/x-midi": ".midi","video/x-matroska": ".mkv","audio/mpeg": ".mp3","audio/mp3": ".mp3","video/mpeg": ".mpeg","application/vnd.apple.installer+xml": ".mpkg","application/vnd.oasis.opendocument.presentation": ".odp","application/vnd.oasis.opendocument.spreadsheet": ".ods","application/vnd.oasis.opendocument.text": ".odt","audio/ogg": ".oga","audio/ogg; codecs=opus": ".opus","video/ogg": ".ogv","application/ogg": ".ogx","font/otf": ".otf","image/png": ".png","application/pdf": ".pdf","application/vnd.ms-powerpoint": ".ppt","application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx","application/x-rar-compressed": ".rar","application/rtf": ".rtf","application/x-sh": ".sh","image/svg+xml": ".svg","application/x-shockwave-flash": ".swf","application/x-tar": ".tar","image/tiff": ".tiff","application/typescript": ".ts","font/ttf": ".ttf","text/plain": ".txt","text/x-vcard": ".vcf","application/vnd.visio": ".vsd","audio/wav": ".wav","audio/webm": ".weba","video/webm": ".webm","image/webp": ".webp","font/woff": ".woff","font/woff2": ".woff2","application/xhtml+xml": ".xhtml","application/vnd.ms-excel": ".xls","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx","application/xml": ".xml","text/xml": ".xml","application/vnd.mozilla.xul+xml": ".xul","application/zip": ".zip","application/x-zip-compressed": ".zip","video/3gpp": ".3gp","audio/3gpp": ".3gp","video/3gpp2": ".3g2","audio/3gpp2": ".3g2","application/x-7z-compressed": ".7z","application/vnd.google-earth.kmz": ".kmz","video/mp4":".mp4","undef": ".undf", "undefined":".undf"}');

window.ZAPiX._zapix_header = '     _|_|_|   _|_|_|     |_|_|	\n    _|        _|  _|       _|	\n      _|_|    _|_|_|       _|	\n         _|   _|           _|	\n    _|_|_|    _|         _|_|_|	\n	                      ZAPiX Web\nW H A T S A P P W E B  E X T R A C T O R';

window.ZAPiX._logo = 'iVBORw0KGgoAAAANSUhEUgAAAPAAAAB4CAYAAADMtn8nAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5gIWCyM7AIx4uAAAIABJREFUeNrsvcmzZdl13vfb7elv9/rsK7OyOhQKDQGwkyCJIk2bYSkMWQNPHBrY8sxTjx3hP8ERDg8cjvDAHigUdoQjbFmWTYVlkerYg+iIAqtQld3Ll6+53Wl348F5mVWFKhQBCCQl+q03erc9Z+/97bXWt761rwAiV3ZlV/ZvpcmrIbiyK7sC8JVd2ZVdAfjKruzKrgB8ZVd2BeAru7IruwLwlV3ZlV0B+Mqu7MquAHxlV3YF4Cu7siu7AvCVXdmVXQH4yq7sCsBXdmVXdgXgK7uyK7sC8JVd2ZVdAfjKruwKwFd2ZVd2BeAru7Ir++mb/ml9kBCCGCNCiA89yHjeh/joa2OMCD7hdc+fe/4ZH37/J5wb8vy1MV4dKnJlP2xhfvLaEUIQLxeX+BE/6vk6E0J8bE1/0jr9s1iXP1UAAwgpx3sTIJQkhoBUEgTEML7W9w6lFSEEpByfC358MvqIVJIYI1Irog8IKT4C8BfgjZcDGX5Kg/YnbBhX9hOGeVISQvhUQH2aI/iR5/QH5098CKiRF+tICIGQghguASnH/z/iFEL8yGsAggsgQGqFVB9yHBFi5MW6D25csy/W9J8ikPVPY2LKqmR+uGB7vqXaq0jKFLtIKW5PcKuB+Y0FbdMyHLc8fXhMnhQs3z9j5zP79M9abJlw+r0T+qZn9uoO7XGNlJLJ/oToQS40NrF0D2sm9xdcfO+U7dM1Jw+fsnt9j83FmnpV0zTNTwa8ywnfeeOA0289Jc8z+q7HOUeaprRN+9MfeKNxg/vgEn5gsfxFMqUVIowLWir5kYX9/L6VVmhtkAKc99jEAmATixCSzWpN3/Uf+1w7S2hPG0xmcc4RXcDOErp1i8oNZmIZnrSEGFnszRmaAZskCA35tEQosGVK6D3JNCVsPJNrM1wzMPgeoRXdqmF1skIXBuM1KtOoVJEYi5wasizj8bcecPMLd1g9WXHx3jO6TYd3nu3FGh8CTd2QpAnBB4Zh+Kk5iJ88Bxa82FWLqqBtWqbXZghApRo7TaifbZncnOKUZ2h6SARCSNp1g/eO9qRm8fo+z753grSKwQ/oqBBaonNDkJC/PKF72uAah1lY2pOa5mzLZrlh99oug3M0m4a2bT8dAOLTwTt7ZYfTbxxTTUqccyilyLLsY4vmxxoi+fEvNcYgpHgBXiEFSqm/sOAFGPoBpTVSKbwbwfkRjycF3nm8dwgpSZKErunG6AxBjIFyUlKUBZgP5jKGgNt6VKJAC0Lv0ZWhO2tJj3L81jG0A+W9GdJKTh+fsndrH6klaZbRbhuefu8Yawx2L6U7a7G7KcF5kr2M0EZIBQhBWiTYaULXtNQXG3RpkblGThR90zG/u8v5+2d0Zw359QnGGvTlPUspRy8dIs45jDF//iTWOLhwcOOAZJLRNx3dsqG8MSP0HjtLx4E91GzfGXevQXj604ZsN6Pcm5DuFDTLmtmtOVIIknlKu2zpNy2LV/cxhYY+Ut6coJAYk3D+7AxhJCYz2DJh/WxF3/YopX4EN/uJMRumsmwerLB5wuZig7XjAotcblJi3O1/nI+3if1Y6KS0YhiGMTwTAm00MUS893+x01AhGLoeIUApRdd2TKaTcUwvh0gqiRscQgmklJTTCu88bd0ghCDJUoSU2J0UIkgtCSESncfMUoZNx+T2jGHZoytL/6RFzwzCQ79sqQ6myETyx3/4PYQAbRTl7oQbr9/i8XcfEetAdX+GEmr05ENgcnMC24BdpKSzAunHNeoGj+wjvR+gjYgjg961DG3P9O4cYw0hjmF0VmUIIZjOpvR9T17kDMMwppV/XgB+niMgYHOxod5sKScVxV5F6D357QnDxJNeK+AskLxVITvBk28/5OBLN1h+95zqzQXZ9ZJh2VGfblk+W3L7Z+8RbWTnMwe0ZzXGWnzvkDNN8JHGNxRZgfeetEzpuwF1mV8P/fAnhMif4OEUSCUQVuKagel0ymx3xjAMGGto6+aF1/TOf/pmFj/4rrzIcc69yLcAkix9AVRtNJH4kRD6L3YSzIuoQ0iB1pr1as3uwR7aaJRSL8LrelPTDz3WGrIyR1vDYn8HNwxkRcZRfgjXNCEEBIxjWAdUqtk8WV965kjoA+XNKW7VgxGkuzmTnSkxRCaHc7brLW7ds16tmS7Gx7umIyZjSB0VmHmGSjS6Mggl6M5astsVi6MFF8fnECJh5Rm6ARsM4ppBFhptNPlhhU41ymqKy6hOiDGNSJLkz9cDxxiRUmITy3xvQZpnVNcmqEShjELvW7r3a4rdgrgriKeONulJbUrYOpLbOf17DTKTbB6vEFJQXZ+yfO8MKRXGWnSpMZ8t8dajtpLiXkWSpwxtT72sKXcnXDw8o942nxiqfowh/EFMGwEeqpdn9Kcti/0dtusNbdtTTSs2qw1KK5I0+VSgPWcknxMjZVXCh1l0CUVZ0F3m0R8h7/7/QAJL8YKYNMbgBkdW5tjEcvr0GfvXD/DOkxUZUghsYvHe07YtWimSxLJarkmzjHJWMjAwG6qRuDTjOHfblnSWIZWkvDPFbwfU3HLxuydMXlsQ+kB9vmFyc46ZWr73e3/EZGeGrRIW1xe0bUeUAYmkPt0QpwJbWPzgKI4qRBsxewnVnSnbx2u8jiRVRrqbYw4SdKbp/cB0f0Z9skZpSXFYYhJLPs3p2pZyVqKVHsncGP8cPbAAYw3ee5I0IdvJ6dYt3aolmWeITCJzTX6tItzQ9I8agoxszzdUexPO3z+j2p2Q3yjZfn9Fvl8hEkm6k42hiRTYwxR7mNN9c01yVIAVEAX18RonPdODKRcnFxSzkjRL6NsfnqfKRH2yR5YCXRq2728wM0v0gSRNKauCzWoz7pYh/IllKqkkAoGxhp39XaSSDF1HjBFjDHmeU9f1C3ArNQL4Rc4rPrimj5Tg/oLYc4LKDQ6pJHlZsF1vyKsCbQ1nT55x97P3aOuWrChww8g/BAE6MZTzCt8NTK7PkEqhjeHg5iHpmyVxiKhs9MZu1SMLzfbBmvxGSWwcwkqklHTHNck0w5YJSZGORBKObtXSnrTM7s5pjxvSIiV9qeT8D09Yn6wwpUEfWpIqQ+1aVK5RvYS5Ig5h5GO2DbqR+GsCPbPU2wZ7MIbNIpF4F1jc2KVvB4pJSdd2ZHmGUeYjc/9nB+APreX53gKhBNObc7QZwwyzk+Ls6GXD+UC8qUkXGd1xQ2cHEp0QCkg/N8HXAyF66ostk9sLhqZn/jP7DH2PShQ6Nygn0aXh9PEJdprSnjUk8wwZBX3dUW/qH35zVhE6/zHw2iJB5orkMMdtem7duk1W5IhLj9F3PWmWkhfFBwy0+ChoAcpp9eK52e6CGMIY1mtNXuQkaUpbt9gkoZpUY3lBiBclDW01RNBaX5Yi/i0lssSnP/48bOz7HojkRU693FJUObODBefH59x45RbODSRpgtIG3/S0XYtAMD2asz5ZopRkfn1O33XczW5DelnaAdpNi9UGnWq8DIQ2oPYs6+9ecPSrL9E83dB0DXd/9j62Sjh99Ix0mpLME+rjLeXRhK7vEAiqL+yQXCvotyNfIecK00sQArtIyGcZ5Y0JQzeQ7Ra4iwHRRIbHLdMv7TJ0AzoxiB1NNsuJMVLOStSHGPiu78jz/M/eA9vE4gZHOSsJ3rN6vMLXA8XNCbEP2BsZbd0iporQerTQbNyW9rRm584u8sCQFRnN4w1D68YdeqZZf/+C/KAgdhGjDL6I+FsC4cAbz+L6Dt2qoTiscJ3DbQbOT88/NfeNIXziBqTnlnJ/Qv+gproxY/n0gqHvKRcT1ucryklJjJGubT8Ik+MHRFSMEWMtfd8hlWQ6mwIR5zxaa9IsJU1TmromzVKm8wneOUxq6dqONE+JEZRUI3nj3E8tpPrzcbN88vVfPh6J9F1PXhQMgyMrMvJpgZQaWyTEziNiZLo7I8kS8irFpqOn9MJTzAuEUiNDHCPV/oSQwOzeLnEI6GJkdYe6H9O392rsvQIjNEFHVBDU5zU2tbS+Y3JnzuZkRXV7jveexZ09Lh6f4856RAftqiGqgJ4biGAPM4RRqOsWs5Nw+q2nuBgwlSU2DvtmQdQCecvgTRiJ0Wsp1dEE1zlslRJjxBYJB9cPcM4xmU1fVHGep19/JgD23o+eNrGk05zqoKK4NiF0DrlrcGVAFxYlFW4B8cJx8s1jrv+Vu5z8xiPyz89wyhO3gWySsV6uufaLd4iFQEw0MpfE+xZWHiUN4oZGe0X9YEPTtGRlRn28ZrPZkJc/fAeTRhLdxz1adWdG33YU1ysGPXDt8IhskpHkKW3doLTCu4C+zNc+7EmeF+elkhTTnOADuwe77NzaHfObGCkmBUVV0Pc9s8WM6c6Mtm7JJyXLswuqaUXwAWM0XdsRQ0Rb/WJn/pG9279BOe5zL6uNHhfjhxbkeK8GYw1915HnGW3TIqVks1xBE7j2xdsM3rN3dx+iYOgcSW4RAZzzbM+3zK7P2Dxdk0xTkoOcfttz/859+GxCaD0qM/SbHrGKmJspw8OG5sGGxZt7nPz+Y175G2/w9BuPwcH+S4ckexm//T//c2xq6VctN375JXAQcoGeGuq312xFg5gpYiEwlUFPDaLSTHdnDLseHRTbbcPyW2dkwdI2LdXuhFW9xEzGGrSeGaQRqNKghWLoB4IPBO+RSr7gQn5STuTHetdYbNcYbdBSYUqLTg1h8OipRc4MXd9R3Jvgqwh1xAmP8Yrte0tEpQiPe+z9gu0fnNMOHdP7O7TPavzFQHlnSj/xmETj00hSWUwwPD07wdswEkrRY4uENE9ZXax+uFPw8WNAEFqiZpr5K3s8+vV3ee3nP0vXdhAhmSTUq5rpYkaSWurNdmSPk+SFKkdKSTkryYocpKSYFJT7FSFEBjdQzSfkk5y2aSlmJYuDHYaup5xWnD55xnQ+ZegGTGJxzqO0IsszXO8+HqZLiTb630hF2Aequ5EfeC668H68p+es/PPS2/O8Vmk1MvER+q7n+qs3cQTqR2t2bu6yfHjOrZ+7izGadJaRzQr8MIyphRQUeyWd76GL7H/mkDa2vHbtFYIKqFSN15UJVG6IbUDfTAm1x0mPyDRmmhAGR3ozZ35nZ4wQSg1GsPr9c+y1lHA+YK1F/0KJaTVDffn9dyzZhSVITzxQpDpD3U6wpaV4fYLDIxYaVw9Ury9o+57QBNRhglSKfKcYo4fdCcZabGqx1mLs6OW99z8RB6KA//LHC6ETgvMc3r2GmVr0xCKFRBYadccyKId9rUA+DXR2wOcgHnvEVGN2EkxuGYqADgqB5OLhKToo1MyQ3CuwWYJb9oibBnEaaOqWam9Ct2xRQkEMdKctZ49OX5RqPr4liZEI/gHZXvH6lP5hQ369pFeOYkiQWpFWGZtna9I0YXW+JMQ4eonL2iRAmqXEEMmnxTihMXJ4/zo6NbTnNdXuBKkVYQh475gdLOjajiRPefTOQ47uXCeEiE40q7Ml1WyCUpK2aUelkvyALNNGvyCA4r+hms7n3lZrzdAP5GX+gm3W+gOBn7WjQuqF0koKinmJEGIktfZKQhfIdjLsLMXXPek8pzmvSWc5/aZDZJK8zMmOSpqTLcVLU6KKDJuBcq/iVC8JD3rQ0J+2mNyiryX41jE0jut/6Tab71yQ3atQQVEWJSwU9cmWZJFhpSHbzVg9WTLZndDHAe89Pnry3QqhBbEUhBgIFoSH1bdPSfcK2pPtqOQSERkkwyzi54HwrY5kP6WPPboRYxXTR/pNz3a1QRuDVAql1IuI5E/dA6dpihsGkjxBFZrmuKY/a1ELM9ZTpxoSQRSCnh4lJe3TLRfH56QhId5RxPuG8HZHt+zYPrjg+tfuw64ieaMg9GPOo44S4ioQpgJyQX/asH13hckN7nxgeboE9UOkhwHMxIxg+HBUmghSmbD/tds8/Z1HFJtLdtEqMBBdACkoJxVNXY/M8qViJs1SurZjcW0XoQQq0+zfP8JMLEJBtihIphmTwyld33F4/xo60ZjccvrgGS+9dW+sY05T+qbj8OYREPHOk2TpWGf2Hq000/l03DQkROIHEys+nUT6aZalpJIfbSj5AfJOyA8YeiEERVXQbBvyKn8B3izP0HpkiPMip2s6lJZIJem2Lfmi5PTBKSJCspehhCKdZkRGVVw6yfHeMbkxQylJPTS4ZU9+vaRdbrEzy+SVOdvTDZMuJ8wEdmIRagRa96QhNhGfBfQiYRCOl/7yyzz5/QeEHKY3F9hFwvf+0beZ3p3jdWT/i9dYXaxQLyWjJ5eKTVoTRCAqiIVAzjUCyHZL3E5kenNBHwbEgUI7hQ8O2xnU/ZRwW5HmGYMfEIlAJoqkSji4fYi/5EueK9GUUT9RHvxjzXqSJjjn2L97iCksdjclmadjqWWq6DOHniXIJtIeBOSOYfUbJxz+J/fY/NE5KjV4G6ALpLOE5dmK7v0tIY1oa3B74G4J6q7GHCWkIqHre7ptR/nGDE9AWElapXTb9hNzRWEkw7L/qGcWgmSWIRea5rtLwtJx/Qu3EUaQLDL6ZU91MMU1A33XjbXKIqNrO5RSmMQwmU1Idkcxxv6NA9K9nGSWEoNg+tKcMDi25xv2XzvCzFNkqlg9uuClX7xPu2nI5wX1ec3Ry9eJjEqsNM/Is4ymabj96h2cczjnyIscrUaV1kdyY/HJoSyMyqQfazPO0jHc/RAohRQvGkmeLywiL2r+z1OJNEnRWr8IjY01zBZT+qYjKzOMtYQQ2b2+h1YapRV5kbM6X5EVOfaSALz52VvUdUM6zVidLNGJZvrFPdbvXLD4wj5KapJZhiksQ9ejSk0yTRkGT6gEcSrJjgpe/urr+LpHag1a0j2osTdTSMHOUh79g3cob015+LvvsfuXjvDe4c5aFm/uI3LF0/eOiY1nOO/I5gXtb63QmaY5dBSrdHQkMY6OJhqGvYi8Zbl4cA59pGta/MrDnsSVATk3nPslslfIhSLM5QjSQmPTZNQBKImUghAiWZ59UI340wqhnyto0jwjSRNsYbGFRWQKWWjiLcXWNKTXCvw0IqKkfWeNP3EU24z2yGE2Ej0xDF/f0rQN+79yA985hvOO9PWKWIAeFL4C4xVYQVgNOOlIgsWf92wfrKjPa9ptQ/gBDyyMGDugXPzYYt/9G9fp6o71b55y8Ku3qJICJSU+BPx2oG96lNacHj8bFWDOEXxgspjQNz2L+3u0yxZbWNJFRrpfMFx0ZLdK4hCwkwRlNJPbU9qzhuZsy/TWnG7ZkO1W9BcN8xsLmlV9yWRDWZU8e3LC/p1Dnr1/wu7BDuen56M2ePAvQmsp5Qv1W5ql4/+XXtBYQ5IkeOeRUv5Imuox/AWlNOrSC2ht8M4xmU0ua/zjZqWNRsqRbIkxYBJL3w8IIS6B2GOMwaYJxbTADZ60SrHWsl1uKRYFrhtVVADrizXVfEqaJ7RDi9sOmGlC9dk5DBFlJaEQyFwjXGSIHmkUfnCEuSCzKWqiaU9q7CJFzjWDH0jeqHj2f79P8dqU/qRFzBXqtYzuny5J71Xc+6VXOf6XD6j+0h7+eCB7fYrMFdt6Q/+kY3IwxaQGfwDTyYRmaAkZhCcDTCTsa0IFqpV0oScWgmLIGI4i1ls4VHgREJVC9BE7S4iNByEhgXDsUJXCLx0xBoSQRB9flJaapkFr/amKv38tD1wUxaUk0JJWGSpTkEtEoogFxIXEX3jkdYMzHnHh2fqGyZd3qd9dol7OkLmi63rs6wVMJZsHK5pHG9LXSnrjEIUk9hF5c1TjvP/734dK4o97XO+Il+FWvdriPnyjz8Xtw/Naj/iIB87enOCe9VRf3MHdF+wv9sf6oZX4dtRtxzgSUTYZweucI8kTurpjdnM+ygET2H3lgNlX9okykt0p0blBZIqubpn8zILmtCaqiMwkyW6Gmhqi90xvzHGMBJyyisO7R6wuVhy8fEhox1LJ+mLFdD7DOz+WorKMJElIs5QkTdk92B1F8pegKsoCYw3zvQXeeWY7M4qqwFr7qeHxfHeBEHIklqSkmlTkRcZ8d4G/ZI0FMJ1PKapi3DSUJK9KkiTBXm4aMUaqaUXbtMQYSbKUYqfEWks2z5nsT1BSMd2b4QdPOSlHr26g3/SkVcbB565x+t5TzEbR+Q5VGIrbE7rvb8l/do5CoKYGNAyPW9psQO9afAnISCwF/XHD0d1rqP9gjlsNyJnGv9cx/IsN+V9eYG+kbB4vqV5fUBUlJ998jDUGcyMln5WcfueY9NUKvyPQj2HFFmYaYQX9z0jM1KK2giAi7a4jm2TwxLF+cEHIBcOTFk49fuMwtaZJBsRU0zzaIGYSMdOYvQThJU460mmOsaOc1liDsRYhBH3fvyAEf+oeOMmSMV9LLNW1CSJRCCvACEQuCTcUlBL3ukI88sRzx2A94UGHqEEeGvhMgvpnHdv1FqklyWsloYvw5RRfgY4KNw+IHmSUmDdzwoOBWHu0NbAKPP2DJ5jEUK/rj25Dl5LGFyD+kGV7OelXF9T/5BROPXt39hFS4mVA9oxMeudpLmqaukEbzeAcRVFgU0v1yhwhJPluib2RoQ9TYuMxNzNkgG7TMrk1x3UDofMM/cDktQXb4w1JlqBT8yKn6tqW6f6ci+Mz7DQhTTOadUOapQQ3KrQms2osPVU5wXn27xwReofSmr7rSPMMm4wsZgiBJEvIypxqViGQaKsQiBfMZpql5Hk+iuuLjMnOFD84bGpRWpGWGcYapntTpJL4wTPdnY3KOCXJihxjDVIIhn5gtjOna1vyalROVfMJ3bbBTsbQOt3JCSK8IPykFKjUYPQI/KfvPeHmW3eIMbLu18x25vSJI7tXMTxtiZlAHGnkEnwawQqMtTRNjd3JkJlCCkk7caQmQb+a0f72iu5GoPv6FgyEM4d+c6wbp70mvzOh3J9w/M8eYF4vEakgK3Pqrmb1zhkHv3iTeOLIbpdcfHecm+gjoo10ZkwVYi4YyoDqJP58GHXPOxa7nzI0A/pGgugj3Z5HKwMDMJfEdcAvh7FRA4HoYGgGfO/RVhNDoGs+aPb4cbzwjwRgKSXFpMJaTT4rSPdzhBKgBOKWQViBPxLYIoFCjOFoYhjebejPOoq9AhJBcy9izyWqtDz5J++R7xW4nYjeseONiki3CMh1JKw9fjkwfH1L9lIJXWQ473Gbgafff/JR1ZIcT1UwNzPiNkD4wBPLQlF97YC2a1n+H8e8/ne+CA6SPCFsPaaynH7zKZHI0PZjh0sEYzRJmVDenJIe5pwdP2PnlQPE/QT/tEXdS5FGEXuQhULcNMSVpzndkr82oX60wU4S9I6lr8ecvG0bFtd3Of/+Kcl+Rl7ktGc1+bxkeXzBZG+GlGIUO2QZySyjmJe0qxabJcQQqOYVNksRSjDZm5KkCfmioNqdsDy5gAB929PU9SjZjGO3k1SSNElYHO4h7Eg8pWVGjJGiKpjf2qFdt3g35v/JJCWbZig5Sj+LRYlUirRIcZ1j9/YerhtIigxtFSFC6Dz5QYlJLWSSzXrD/p0D6lVNeTihO28xqSUvc86PzyimJflOgS/h5Pces/v5Q1rdUd6YImeKi7fPKF6d0j6pR5JzHWjamslshjrStA8a1GdTYhOJE1jc2OX9f/YO2Y1xI5AvZ8hKI9/1pCQkbxR4FSn/yg7db6xQn0lRmaZpWh7+T9/j+l+9g1eBtEgJF47uK4LOOmaxon8ZVCeIlSC6SCs6FIrl22dMp1NWmzVplkImcGVEo+l3PWo9Vhfa4xqjDQwCv3Fj73HriYzaghgiSoyb7g/VBPykABZSkJcZwQXmL+2iK40oNcJImEnCjqSdDYibmiH10AnCjmD49SXzf+ca2z9ekd2sEG1g+HZDf1yT/OIUZSVd4tAzg/YKP4mwjRirYaZQ741hicUQNo7tHy1x7cD6dDWGyBJkqoh9oHhlRvu9DYj4ESWQeatAXUtw77bYX5iwSMaWsSE4RB9xg0d5QbNqx5bECK4fmBxOEVpSvDGlfrohmxXYr05Qy4CZpIg9Rag9rWtJ3iiI33e0ywZ5OyF6EFogJgrVCmQq6UPP/GiH+mx7KTN1RBcxmWH98IKd27tsLzZMrs0IrSfbKyCAzSymMBTzknxekExSqoMJamIgQL5X4F3A5Aadjx51OpuipKZrW4QUTOdTsjInX5RkOzlJlWDKhGZTkxQJ5f4EkcqRUa9yEOMmZicp5dFk3KhcpDgokem4ibt2YHJzbAP1nWd+aweTGoSQYMaabXVjyunZKTu39mgeb0hvFMggEUhi71m8totQkia2HH3pJg+//YCdLx3SbBqk1ci5QnSM5SHjSG4VDE873MsSOR0JH+EFVDCsB8xuwvYlx/Cba9xFT3i7w/7ShOyliukXdrGnkmZnwHXDWK24kSEqxfrRku53Vxz92kvjmlpoNIrttsYnAbUUuCOIu5Ih8QQV6XyHcCDPgRsKGw3DxBMOxjQwTGAtt+SPDa6MuHpAt4poIrKThM7jWgchIoREEOl7N5aqftoAjjGOBEqRYXI7MmaFJhQgKoW7BbXqcK+OYamOiu16i3+nYxoLlp8fUFvBUATshWTzZEX2V+a0XU/IBe6uwMwShrZHHSXooDn7gydYYVFeED2w8gydY/nOGe2medFNpIpR8dIe1+N1VYbQBuzNFL9ypP/hLrHz+DwSf69l/+4hJJJw7pCpImw8UoFEcXF8hjFjKSwpM8x+gr2T8+y3HnHjP34F97TDTBPa1wJRCvx6wB5leO+JKtJ2HeZaSr9sCbuCYr/i2TeeoF5KsTbBDwNiT9O+s6W4WSEGQf10w+KlXc4fnKKtZfP4gpu/8jLb768oblTYMhlDU6tI75TIRCMTiTSS4tYEbTSmtFBKtNLUmy02S6jPNzTbFikk1XxCNs2RmSI/LEiqlJhE0jRl+ubeuOtbgW8d0qpxvK0Yj46xknSeofcsSmv0VBNOYJcKAAAgAElEQVStIJ2k+N5T3KhI5zndRYNIJMRIkBGdWRrVYHYyRBMRuSS/OSFuwli58ILt4zXJLCO7W3JxsUQPAl6z+Gc9+uUMN4XmO2vMqznuuIVU0K5aZB8x2hIPBE3aoWYWcWjY/s45w26k/+6WeEcT3+0RR5q9v3qdx//NHzF/aw/5UoLbDgzGk9zMGHaAc8f2bEt2UKCEQi8F/dQTnzrEjqK9HZlQMlymd0KA6iV902EGTZcNJM8kQx6JIpIYS6/dWEmYytHheUF83COFQgU5Nl8gXnSmRRdo62YkBn+MQyQ+HcDig3JFkqUYa7BVQqjd2DM5A5kb/F2J/1aD/GxKaDzkoB9G9OsZ6jd73JsKsY3Etce0ijpt0XdT/LsdvGmJU4mzHgpJ1AEygT91xATStWFQA3ojWH3zjCigXm4RcgS9Xw8Utyf05y1CStTUkN2v6B60qFfG/Ej99Yr2/13y6n/0FqFzqFTDOqD2Ld3bW7wLnD86w2iDCw6bWxyeyZd3aE9bsi/PCDoiPp/iCfgjiejimDrcE8iVpH66Qc8MfulgoZCloj7ZkL4xwT1qyW+VrJ9tCCtP9cqU8GRgaHsmt2ZsTje4xtFtWsqjCduHK4qXJ6jUoDKF3DeI3dErDPNANJFsUdDTU+5MRoXbdAyp26ZBp4ZqMaE+X4MQ7N07oLw5wVSG7BdmUEfERCH3EyKR9Chn8/4F1Y0Z4UBQ7JR0mxYzS0BBbx3ZtRJfgs41IpPEAtTMoqJA7BhMYkjLjMENmKiJU0FyUCD3NE+fPGX/zSM2373A3s4QbUSnBiEE2Y2Svu+IucAeZDTLBvVzOfGRQ5SSbm+8XxGhuwlWGNbHK5IbOfFlA0887hVJbD1xJlkc7fCsO8X9bo28bhAThak1B29dpz8IlLHg/Bsn6J+vcF/fUi4qNtQ0JzX5bkFOip5bzk9Omd/fpUsH+sqTPBYIC+2+w80E4jdavAo0bUsXOnKZE3bBJwFtNc1sQE0M7eMtcqEJEsLjHlxkWHYkaYpJDK51CAG+9zRNM7ZcOvcjn9DyqQBOsxSbWrI8I6sKbG7J5wWmsKipQRhFMBF3Q4xdP9c18jwSQkT8oxqrLeGbLWrXwHcd8TsdjWsYpCNpDCY19HOPiAKrDP0soJVBPgvohSF+p8M0GlIx6qcfDRx/5xEogSksrh1PNuhWHXf+vVdoLxr68xbcSB6YL5SYf39GfDQQnzgKmZPKhKHr0Zkh1gG/GaCPCKDZNCilSI5ypncWxNcMy2+csPjKIeHLFv1eYPvzEVMrCJH2ZsQ+VXSio5U9cqYYCk8oQe8ntMdbvPCYL5Y0b6+x0wS1Z1BOEVQknxW06wa3HsBDwKMTjcwVKteYucW8VYx5VRJwyqOnBrOf4eeMEsEdTTe0yH1DbTuSSQKZpH/WsHoy1lYP3jxC38lBQ7iuEJVi8A490eg7CZ0ckAvLIB2hDzRpj55bYsZYQrGCofCog7GOryeGuJAEHQgTiUQgpxq37kdlVhowuSVOxZg6/Oohy2+ekd8sGY479FGKVmaUOTYD6SKHVy1BjTyE+krJ8KBB3LVYbRgeNjBTxC4QbircwxZ5NxmjPRQ+jfg8ghH4Jx3N3CGeeeJCIc8j0189YP3bp+hzSf9KJF7XxGuK+A83hF/O0EKzfrxk/U+fcf2XX6KdjfXf9V5LW15KKQsJO4phEvBmlGbWdY0sJfYgQx4ZnPe4vYj3ge766IjiqUfPEgYc6n2P8AIRBEZqYh/om7F7DR/p6pZhGMjzfJT4/usAWEgx9vvmGZPFlOmNOdWtGbrQqB2DrDR+TxBT6ObjYWKDDWz/+Tnzs5In/+Bd5HlEvZLBQ0+0UH9/jb5mWf7mCelRwWa5Qa2gP24Zlh3sKVznSL4J2XcF4pGHShKeOvy3Wrply8XDc4QWmNISe0+yn1MdTbk4Pqd5uuXl//Sz9AzIQ0P6N+eoawn+Qcfk/oJsdwwj2UREEPSPGmQY86nV2+eUuxW9cbQXNduLDa4dUDcS+JsFnezwB5KwGBdsXV4C9qKjT8ZuosE7nBvgtYTNPz5Bfi5jwGHjmG749UgQtV1LqhJ61+POBoZNx/Z8S3FYEQtB8lKJ7iWN6XB3Fep+RrdpqGNL8mrBWbukUS3FV2bUNMiZxk0CyY0c+YWc7T89JckT1u9dIJRg5zMH9LrHvSRxaYQDhUo0/suGWAqaP1yhDxP6eyACxFLgikC9qkcRwz1DINKnDj6T4GuHm0Va0cNEEnQkuV+MBxR+rkI+C3TrjpiBOkpYDmv6ctSyZ9MC8dSxPd6QzTKii6hrFo/ndHnG5I0Fm+2GeCjxNiCCYHO+Jv5MOrK5hUedCZrVFt5IcIuI6MFfE3RywF9X2Jsp7bYlhoDaCuTfmSG8JHm9QPaCNh/wX6/hSylhIYkLyfbtJf6sZ+eXrtPXHboyrH/7FL8LogV5wzBcF8gBvIVYQdx6TK1QJwLRQ/PNFf13a3RmkLctQQnU3BBsJNYe6ohuRg5AxzEPjn1AKUm/6fE+4HqHTROay9NgfjIAi1EVouQoRg8xoqREFxqsQt4whFLgdiPdtcBFsiZ5vWTzysBQBeq3l3gV8SHQfUVir2dsfyHCDYPqJBePzkjvFpwfbkn+2oz2XsC/ogmDp/7eiuXmAvlqSlgFEmHhgaM/bVk/XtKs6lF1ZAQ2s7jesf+layzfPUMvEmaf28N8pcQdCtzhmMsN36uxmSWL6VgCqAdUqhEXcdS5bgJGaJbLJdlOTvXyHPHFlPqdFVsa2v/nnK4e6I43eO/ZnK0RVtC9U9Onju6bW1rT07y9pj2u6UNP2NcMhSf77ITmWY1/1pO8VtLlDtVKgor4zuEbR7/tyI5KXBjz8nSekdzOibuSzU4HMqLfynE74CuJfiXF3sypfYvYHcUY/X1BN/eIJ44hdZgiYfnNU5CCyZcXiLdS+JUcXRraHUf9ZkB6SUcPbyW0tyJ6KxjeUDTpQHfWEA4U3WzM290tgSsiXd7Tvwb9qmd4SzIoRzSC1dmK6Vf2iL/XMjQ9cqqRpaIvHHEuSL864/R3jom/07K9MZDcKtByFP8roQgTyH9mRmN7+q+vCV9K0E8j7YGDStL++jlxCDRfX9HnjviHHd0fbzFVAguFyBQhenhvoBeOft3R/71z8GC+HZEd1P/kDDMozv63R6RHOe2zmiTPEImkXtaEb7UkZwrxOBAfO8Rjh6kVOtHop4L0mWR70BM6B0NEfztQPDSEJwP9k4b+WUMySbFVgnjgYaEISUA88TgdGM47iiZFriOxCeOJq2Esf/ab7kW3m1KSZvujAVj/UPCqUWan9FhTDC4wbAZ0KuFsIFbjhPalR04UzcsRKoVaFMSfK5h/cw/3fsf6tR7z1GEfChCG5m/B5G/dpfURaxRD9IjdBFFKogD7miEsHe5fDFRlgfMeeaAJpUa7BN6F4qiib3qEkdz+pbusnyyRlWbnzQNMYXCpo2168r99jXDek2w8OiYMLsJ3W0xmxpMvM01QcP5bT8n3ClKbMix76vMtKs8Zfk5T/udHiNsp/qRD7SX4Jy36MMHVA3QKMTeEn7fgImo+hRhx32kYngyAo/2dx6jSUn4mx4uIPxlQBxb3fo/vesIw4JNA39ejNPWoQGWGtu8wuynFoHjv9BHmrYooPP5kwFzLCBcjR0CIxM1AfCARm0DcUci+4/r8EDO1OO/Y3vJsHh2z/N0Wmojc0YiHAnGoiU2AY4eYaoII8AcD05cXNG8EvHUIBF1REy484oZGbCO86xHXNJwHwj5wJDl8NOXkHz5gf2ePxGZ0TxuiEkQ9VvWevfsUNx0o/osF1e9owh/31JuO6uUpIXrMTHPy9x+x9Cv8V1P435+wuWkRxiATSdfW6JuBUI/5of7lhGggvKFZv32G/+0e+2szHA3+4YC6n5L+Z3v4RwNqsLhfSpFTWM97std2cFONiop2XbN2DearFfJ+gvv2KGzRvYRXLf1nYFluid+qaY63pCcT5O0EkUTCVwKr767o/+UKNQiqv7ZDP434u5HhSUf/ZI1/p6O4P8WWKd3E4c8iwXiUAaUlXisIAVsmiEbQNR3OeYSUn9zP/gk0Vfxw2KzUZcugNZjEkiQWaRS2SLB5gl0kmMOMmAXqzwncAVy8UsNryY9/YsMPOa8KxtMgr/0PKc1yizlRdL+/4tkfPaV5uGHxuX2685Zu2XDn117l/P1T8r2C6Rf24AsJ637L8pUG7llA0P2vZ+QqY3qe0j1tmYRyVHx936EHhXvccvb+KSrRY3P9NcPZe6fEA0X+66/yoivi+end8dPu7fIFH/pFitgF3G9vsa1mQoF4EJDnEfmeZ/WNs7HpPNck9wrEZ1LEv2qprk9oHza0s4H11wTi8+nl18ZPn84Q4Rs96X/b0P36Bf22Y/6rR5wtz0n+3j0i7ocM/HjdAsXw3z+Dr6bolzM+/ST2y7ZCJPl/tWFnMideeFSraL6/ptkfUPdSLmY1wy9qzN2c4f9ccvj+FFtrssca/6yjW3f4AvpfUGy/GBg+rz90RfEHlqq4/NO0/8sx5mvzy99WiJ94fQLxkXEbPyGOpSzix96XvS2xg6brevp/tcb/3cnlXcY/8UiSyId/ceRyDQQITwfMA0hbg/i/GlKVkJyoUd31bBjbUc87fOdYPjyj7we22y1DN/x4Hvi57laq8WC5LM/IZhnpLCdqsAcZfjsgdsY4Xs0Fw9wR52osv16OY5CR5FsRe6pGtvfA4uoBkUjC4IlW4PGEPYF73MJXso/9JEv+rwS0EfUIeDYgpKTfdOhyzMdMaXHDMDLbRynFtQm+iLSuZnuzJ94xlyXhiP13Z/R/f0l7K0EuJU5H1DccIYPBjycl5lVJ61rKnYpwQ3LwuZLmb2vMP/bE1tPdj4Rr6vKc4MspEpHZt0evLTqgDQzHDfGeQS407WtjTimMxPzCBP+k5/xfLJmWFfGpo+s7ss9N2Lia1nj8z0Lyfkf5VkXzh1u6qUe/lGL+xwvcf7dCvGKJP5fAV7IRqOKDDiz/uKP8DQk+jgcDigQfJbJIqY6miK9VNP/1OeZeyvbhGvl3F/8fae8ZK2mW3vf9TnpThXvr3tu5e1LP7HJ2Zna5y+Uy7DKv1gRFyRBpwbYI04BgCJAFA/rgQBsWDBiwBCfYcvogyKBkUbZAyrAgSjYlM4nDFcWwy42zO3mmc99Yt6reeJI/nOq+Xd0bKLqBQTca01W36j3nPM/5P/+wPpAE/rWW7KsBbjnETcf4p/cY/qcTxJ/JqOlQ311CITcOq+gC8RcWFNfGiFsOWSp85+HYE1VAXDcEb7GuJ3+2wu8FovPoHx1T/+2WcjXFOot+qqDarujfqVn92jH6dyVhzyM+lGN3AuKDOTxn0sI69Lh/fIr9pTlyS2PGhvy1BXxnQTMb0N8/fuJwHf7SLcydSG4K4q5ka2+L5oOB5T+5T355hPuhjPgTo4eupX3bEz9bI+8G1B+25L/p6GaO/DPb1C961AvF2XsEkIvI+P+NdKsO/RXP/j+/RfZTM4q/cJ4wTWtFXjK4S9C/5tF7EIQk1gJhFKJOFrWqUATrMVWOC54sy/9IG3jjDhxDXLN3AiHG1J5FMKMM3zuKq1WSrV3TeOXpJpbVSY09H5Gz5LgnBpj9U0VxqtE3Ikoq9LaGQ09+XzJciajjSBjBcL/FbwvUuWxjcZRvKPJ7gvKuRlpBMJG4b5nfOEaPDMpI+nnL1R+9zuL9E6YvJCqeqjSt7liqBv1scfYctSCuPDLXlJ1GGoW47cmEQeWauAoMdYddDUkxcq0i9pHqygT/fs/o6gQ9F7jWEi+qR088+I2aosvInEZ3ElmDupKjbgXCPUt8Sp2N40YKnjEMX1pRHmsme1PabUs/ddgfNrjtSL1syO4Jhnpgd2eG/70GMQhKcoppQfY+NO8ukB8pH4kRicQ+EP/JipEoMUcC915H2LcoryimBabMKKsC92bLwi4xn5yCEIS/fcLOv8jwN3rEVwa2nt9B/44j++Epzd/bZ/rSLsuvnqBeqjY2RrzrMG9FdsbblKKgf2tFRQlDgGXEBUe+XbLYbVncPyX/5NZDZVh5QxFiJC8y3O2O/o0VapxRPFVhvmtEfyWiPlhRyYJ+1SOeyohNIHsPsvMVk4/sYP7MDHkYkT+9lYrOYcROAnJy9nyCiOyMZkk48pk9zAsj8jxjfnDC6M9fQr0VUEHRnjaoZ3NEBH0Ahc+Z6jGTi1uY50r0SxV+5Wm+PEd/z/gstiUm8c3WjYIi5qjrOVvfvUdxZUwZctp8QFSJHCQAf14h9z2jkwzRgmgjoUsTEN97gg0E6/EuMHR9SnD4lxUzxBhx3mH7gaZuaBYNzUnNsOro77SEwWNPBkIfEEeBuCWTWz6Ah/yuRIw1wysS1QjCLLGd8iOFkoq4rXAqYOsB5x3m5RGPdh0IGH8Wwns9TnpsN+Bu9oi13lVXBpHrRMYfKfQsQ5Y6SRfdivp4RfaDW5snsU9aTnfS0WEZ6oFwWRHOS8KpgzVzymQmCcnznG5mCa+uqCYlupZIrdB3nmyc+mVHVmXE13vc7UT0GP9easOqGwb5vtt0niwk/hL0Ox73TDrF3Z8tyT41xXx8TP6v7XDqV0yvb9PfbXErS1FrcmfIvhwwK8V4WeE/32xQSfWFnP7jktXrp9gv1YQ68WyzcYY96uneWxHvOY7fOST7V9Jmsr9whPp/OrRVbL9VsntxD94ckgTwswM7L1/AvB6ojgzh3rDxnOTVDHKIf9AhjjzbF2c0NxepCExBTDXDrkcKgfn4OD2OtcnC8nKPHQaa/ZqubjHjHD3WcBgo5oZKlsRDi9sC1w2pLb3vkEEwumOg9pRHmjLkmBuQBZ14+F9uNu40AkFWGNT3jIhbEpNrhiuR8tKYMJPEaxL5o2Nmdkw4SeYQcVcR71n6C4H+Y4LFpCa8aJBaMP3ADuIkbAaYKVBbhnBeEp83xEsqkXqOWvqfP9yIThMh4j+T04aeoe9pm46+6eiXHZFUPKVRGGMSBiWTflpI8U2vod9YjRSSDUrXddhhYH7nmOakYXXjFLe0uBstsQ/IQaJXpDmvgPHbGuEE+alCNSJ5CdU6oYMTmTjDgJoY+hs12Y9snfGWSa339FcEQYLYT5Qyd2wJ9wf6oza1I0jkVFPuVKzeW7Dzr16B8wq/HXGlx15b79l7w5k/swT94SrZo/gAI4E0MlE3u0gsBNoY1MiQjXJyl2NOJfqFCtkK1CnkKkMvxGNfU2Dn2XN0TYepJbpTKCGRTmDehhg96s0IPp499AjilRJRKezhgLqWI68UZ6f6SFL+wBa2sdjWIuvUHoe7FmEF6n5E/n5P9osdofNnoW8hYn5ixlLV+DISBk8cC/TEMDjL8nTJ/rv3iD9UYj4yJt4dKL4A2xdmDK8uiBriGz36WBIXDnMq4Z4j3BkQI4X93OqxC39EvlJhnwXRQjzymCxD9gLfOJRU1DsDPkTUR6sNY/3wnYY+DHBJMxqNKXSOOhVpTl07yiONsOC+UD/c/OpmoHxbwVQy+rKiONBJjLECLQyjvTHyvHkCYOm2PZXIqe5q6IF3HFVWoY4iyhioA3Tps8f1M40nHnnPoxrgvTQqykRGdWmMN/GRKxR4HejHnr6wxAICiXRCKchGSYn26IYPBrqZxZmAmCnM+Zx8p6TaHVHtjhhtjyi2kuBkNE7KMqXUN7Xb+aZyQqUk1aiiHFWMZxPKtXG2KCT+1CG6iJoaMm+IhUC2ULynMKcSsYzolcRWPs29jMRlgViSFBkzTfGTO5tsL8DMBSoqVJusX5l7Qm0ZtGP/nXvIXBFMQOZJV2x2c7wKRCJxSxE+oBDfUaRd8mpDrB/98gTy5YJwWRIzQZQRWSjkrkF6UmuOROaKxZ0TTJmRBYM5kPjgCXcH5rePEI98ZQKB34GJHyF6KGKGfjOkNnxQZDqHffsk6DWVRBPXLXeEU7+Jfd3wmEmOCjLdb30gLBx0keFWS2YT68n/tQN4kNy4bqXz/+4qbdbhi5D43ruG9qRGzYGPFeQ/u0vwHvvnbqG+7Oj/IEXK1F87wa0czY0l8V1LN2/JhEFEyagryXUG/pHq4yFWsLg1x/YWVWrEAM475EgSfaDKSrLvGz+x+GSuMD84ZXR+gr5W4HKf+M8XM9ydHrefCCFxW8BYETpL1RaJCtpmxEoS8MiRRrzhQEXE3ZCq6GP4aLaQSdm2LwhNcjrx2zF9H1Kg70fUAWQLRZg7/DiCi/i7Fg4D+SRHHHocjtB6Yr9ZgWUQGCfJeg1D0qSrMkN1ktErM/y+3bx6SKhe3iJ/pmL03JTR01uYcZ4E/iIZ+rnBMXQD1g5Ya78lM0t+CwkSUkryIqOcVkwubJFPCvKrFZNntiGTyAjWeDKrKG4r9JCqr0CgVgKfR5RNmlPpBe3MoVvJSXNCGG8+VG89k1tFMsw7ElSXx8gmRTkWF0ZEFVETgzmXPuzkpV3Kl6b0w8BQeUJwtAct5nqB6CCTGWr5yHv4iLhssLnHO49TAVFHxCypbUQuz9wijzvURKNPJdx1+Ay6qUUWT07dwt0BmQnkeUOhc6gk3HaEArrbK/TIpFjVR9uuPFK+OMVOko3Pzu8kF85IpPxNz+SgoHttgQqS8ZVpUm31lu5ujbvTMxIl/nM1+vMe+2vztIkfWVD8p3uEZzVcVuirOX4iaJ6yxJ+dpEjW//KEgoxwb8AedCy/foxC0xyuEB5cb1FD0gtXOxWyjUgvCU3YiJDpz3lGz29htjOGgxYR0jMnCprRwOL2KbV6MjFSBGh3B5aLU4ZVn7zCdjKwAb2dsfBLsk6zOl2BhGzI0CeRrNPI41QEwn2HRmJqgZ4LysbA7MnlXLQZoYo02z3aGOJVRbKn8ozKEvd2j5op4usD/p+tiP+sgVzgosPdG5B5Gs854Rm0h3ZztBMVdOc9XqeH7K3DTExaWxP1DSN9/NLRxYFu3tEd1gynHe1xQzNvGJqOGAPO2lR0pPyWuV/yWwHjSVqXfoBgA2iRRiKrgSATaV1KwdbXCsq5JhQCaSVuJ6DnwFhgdzzeB/wk0sWOZb9Cf0f1xL138naGWkVkG3GtRRqFW6SBOXLt8C8UWVUwvTKjmlV469PP0js8AfViAUjiax32uCP86vLMZ0iCqCTCCrisEBNBWHmijqjz2SNOkAZjMso2h9sOsaOQxx4RBLJQj53wka0L24mMMNK46FAzgw4KdpJqJ/YRER63wpEM7YB8Pke1kmwh2fn1nCs/X1K+o9CDggOPjIL+XotfWvCC+t4ChsjRV+8Tbgxk0sDfWqZOwz9yyl+UtB+H5RdP6HYc3dDCv72FHGvsL52w9bWMkaxQncCukrrr8N37CcQzGpFLyqxguNkSTwM2OooTTbzrklnCAx+ubYPvHO39GukFjJJYP4jEE5d7KvmkhYi/0W9URn9BoJ4v4eUc/R0F1lnC3NOFPtFqhwH9oTJdK/6wQy4kMlPoA8ikIX8tYk4UVTlKs+qnIvHNJ0UAQgm8iTSjAY2CicKVqT0OGuRxQBSKOHfIBeQySx2UzsidQaPRJwKzl6MvZYhSPmlttEprU3USESX2fk/cFdi7HWKmN1sCF4ltAqyi9QST1Gr6YkFxvmJ8aYtiXDDenqAzk9xvvpVBw7dSIBETCh19QsekEYQ6vbmwEScCakimcFiBdCCjwE4isUvcVFsFooB+21F/4RSeN5vmXRJ411LcVsQ+QhuxnQUXGZouidxrTwS6gxpZpFFUb4fU8kqVjPS2BOL5LOl6f/mUMPfI40jsNsXR9qOKYRiwZSBsp3tM3BLokUYKiYgQeoeuBWF9kKjbEbGfmDWPlhOJ5P3bN+hcn1hnLwriXUdX2eQaYgK6NKAfAyFCRL7n8PcH5FThYkCViuFaxEwy5os5k2e3ESegcsXq5oLV4YLF4QLbW4Z5T6gD7m5PflfS/zs34FFPLA/Zv7mD/T5N3JHo/2AP8+Ex4fbA+O84/O0B06m0YZWinFSMtxK6evz+Ie29msM7B4wvT7AzT1mU5Lsl7reXT+TZ+2sScV4TryjMVkamc3wVcMazOqrRlwsYQN+KG5lRIYPhfICFpz1qMZOMYdsTn9cw04Qioj6UbHiqJifbztFBJQMGFLQJWzAxgV+mk4xe3n5iXusLYIh4FbEiYSDBB+pXAvd/sk0VdhlQRlFNSvzCJX/o1uMGi2wgGoFo0kur/Btwn6REGPCjgNDQ3a2Jy0D3tQWy2NxiYkjB9GIA4cRDex1hI3EIuGYguEC36ujbjq7t6Lruj7eBH1ytvA8EF5Ba4pvE3xQtRDwqSJRVYEEKSSDgt8DjkYXC5wEnPfW9JeIjGeRio/qqlaBYJGGEaiXBBlxM9jkxRqRW+MYhxxp3NOCLJDoY/EBXOezI0xWW+TvHyEJhf+0U/WyBPe4ZRoH865vvp6eGQVn8FsRKJlCilGn8oJOfdHapZDjokF4iF4H8qVFy42j0xvKIRGZsMVIjGAncNCYl1UUodUH/XGRZ1Gna/mjHsQwsj5c0oWPlG4YLgeUVy1E+p33aI3YUYU+SXUipBcWkTPREJVkeLqgPVjQHS+ztluGNmvoX92n/6ztna1em727815/m8Okl6k8m1Fn8+wdorRFBoKRkdCnl2Np2wNuQTBoEjC5M2Hl+j1gHxHue8P5A+FJL7nS6R8azVrj/qEAogXaaobd0Q4ffFvRjj/neZMMU3+wJ9wbC3D6y8AT1Vk/oPUrJJOPTmnDq8NPIabdE5hrRRcKtAd1JxA2HWEbkKql+RC5oTmrC4YBvPM2N5RPMGl8FVK/wWcAXYKeBUEHIQbqUXyRFQnzDHUc4GnCdBUHazMeJj21qgT+2uPnw5JVApdxr0YBpFWGZWHLyYpZGjQ9ALwnqzYBUiuA89GnT4iL+2BI6j11avA30bRI2OPutlUnfdAOHmOIbEfujADQAACAASURBVCJRuiIIqQh98ouiCylOAoEIIG1qnaKK+CKkwOZR+gKH0Ce/oe+abCJyMlK8LhitCkyQyQ7HQ8zWv4uYZHlHq2RdWyj0VKOyxH0VJYhZsvLM/9xuGjPdjuinSvILJdnFnNiEJPp+BK0Nz2ncToRZArPCiLRY8kQflVsa1zh854lB0JUWFRVuGp5A8+3Y08x6VqsVeiXodh1xIjn90MDq63Pi9xWbDzyA/qqnKTraDwWW3+uYP9/SPG2JP1hy+gmH/6mKYezw1xTZ+QpRSfJRgVIqpRkIUFpjpKGYlmSzguav3EyE+UdNLLc12Z+cpf//f1iwM9tlurvF9PIWrgjJWDw3zK7u4pxNxvWTEfXdBfU7C5bzJeNQoJ7OcfOB2SsX6F+db0wOqCT91OOvC9QLOfKcRuSCUEW4nkQK5jcHRuMx8k7c+B6GK1BfsfhnNG4WCRNBaAJhJpAv5EQC5cH6SlJI4i1LkJF45IiFIK7tgAUSVWjkY8tZAGKRusWwcCgnCEtHIBB202EVfGA47RJj750V/laf6KUq4SbpehIRQVKJFDu68R4+ifpVLdGHAnUMfm4T8eXTa/Q9rDkDn21QrSDokPZUSPss9iH9HpMaC1IixR/F6P2bg1iPAi8hIkSinYUhAS/piwNERDuJWG+4B7M+pwNee3wMdG7AfGK8eaEXkL8HWaOSs0Ev0X5NzRtpovIJ8VWCfKdAl5rsakk1G1NcqJC7CnY1YizJPzyFsSJ2nooCFSU4kWZ0XuG/9kgEqQD5TIY/tbjtCHmqIF56zNgkJ412nasUI0JGWHj6vse+Vm+g0ABmL6O95Kj3epppz/B0pNkaaFYN4ZMFcqI3UcgTR/a7nuloin5ljH66RF8qkCP1sDKJ9x1dNdCbAbe9DpielQgj2bt4Du8c1daI889dxA2Wix+7yrlPXmH+ypcRSm6MrFDg3+moDg3xqsQ/p4hTSXV1yvjClHy3pJ03KK3pVi0ByCcl1WiE6TTLuoa3eoqrE/p3lmSz8qxdF+n1wysGKz2re0s6MbBSLW3fpgP3VDC7fo7RogAXNmfiQB0ahq5PdsMnHl1qnHKIiyluJvs6iGVAzkOqVnVIJvFeohqZAvAmKQMpv1ZutNACwSlLmqEhLj3L1RKLpf9wytwCiFnCQkLjsAcd+U6SXYpCgZKUL0wRM024JvHjiMjkxp022kD/lQVhaeltTxM73F6k+46I2DOpAJ467N85RBytC9ODwI1MEGQg6MTWk4VG5QqpBcWoIP8jGNx9SyNa5x3O2pTdE0izxRgRSuJFRDqJKwPCCmSUCaJfu3f0257gwN+zyI/m6UB4dO13gfy2RveKGAJyEFiXkgjUWOEfpC9q0HsF+rAluzoh2y4QucDuBbwJ9JNAu92jKTCvReRTOXEbiudH+EoiCsHoMKMhPLy/CST9pUB/p0eWmmKlCTEipxpWIaGtMp1ETkbiwtNk3XrOuHkH3n/1NvYfn6Iu5dRXT8meK3E7YP7EFsaIjQMxrjz53+hQRuFuOfiNFfFT5cPW9cGey69WxHcblgcLts5PkYNh0m6BB1sPjEMkyw316Yrz1y9hXqzIjmrCM4ruF/bJf2ZvM2Bsz9A+17FlS+ShhCnI+9CsaopxSTfpcP0SISWrkwXFpGAYBspxidYGtgyxB5t51Oda4ic2M6n60KPe8skNpQjIbZVcHQtJvOtY+Rr6gPzcgP9QtklM+K4C8boh9BKsAOcILiLOaWQNrrWM8hx5CkFJYheT6Z0FmkAsBUFFzLGgm/RkZGfPKEL/iQclc0zzqIPpmqfsxh5ZQ6g9yqa4oNhEAgGjk3RUDRLReaQTKepWnJW/MBWc/gXFKf3Dv4xhi3jL4f/hCtsNyLFCP1+ipUlrUIpkNesg9hAzkE4ma2CliES0Vgnf+f+zgUNIrTAiVSRvQ0JztcCRvKQkIrUYkiTuXwwIJ0FEhsYSXpYPiR6PLqr8HYU48RidfH1xEekhKEGsks74geOljArd54y2R4mLvKOIFVBGvHCoK/maixyJM4nIIJvkyCCImcJOQM0DYfrgUh+RL+R0twd0iCgtEc6SlZrokn+RyiVBBqSE2AVMo/HzAf3IB4kxUP7FS1R/8cqaGJ/MyXKZRAVRiDSjDp7idyN8qSefK4IKiElE/7bFvmvhz29vdCdiHimemTAa7WJeDwy+pReWrEp0v3yrSJUnVxRPjxiUp7w8xu5IOG6JJ24D/RQTRfd8ZHQzEk1gTE5f1+gLOYvXTyn2Clw9IJSgnq9o5zUqUyy7U+RgICr8NUWoItm0oPlag3pxTeWM4K8rvLKIxiGioJc9+lMpZaF8A/SQdMjmQkX3GwvyP7H9cLoxXIsMNz2yT6PEfuwYdgJGSsLdDnmgiSJg6z75eHcudSlCIJxAIRC5IRbJeOAxuB/+0QpZKYbTnuypknBdp3HTGuCRU4M77hAjiRkZgg+IsSS0EWEEfd3hJ4LeWHSfRl08wvsXHszbEbOQxNOArwJd2yF+aIz82RlFjMQTR3gvZSXJkcKFQByTxoungqhias3Xhvrr1vaPKSd8DMgKIaHRYY1KB5cg8yiT9SsiVU1fJd1w1ElCNoQBn0Xk+XzzZxFg3gkYn7xwlRcEK5B9AoWijISK9G8LnWJPCoGoBGqqiTriM4/NHd2yw17wKCMR7zuKE4M4CJAL9InEFgFtkxnZ8FoP35+njSITpdHtQjwRxFagL2XII4l0CiMNvohkOznyaoYcefRVGL/f0rOZlKBaiOvERuFTBk6oPQyBojeIg0i5KqjfPKVqSzKRTMtXbkX+4pR2d+D07RZ9/eyuHC4pWIIdBsII9E7GWCSiyaIZ0oGpBHLXMBx3ZJdH1HlPn1v6HUe+s0bNHjkU9KfG9L/ukTcC/bJmqxgRjyzV9oj63hLrHaFx5FWBzDTeerLtHIVB6YwYJX0fkBcDi3dPUC9WDyudKBLHWzgNBXjdI68VROcxdyC7JxiNKuIAfETSWZ9afZG6oXraIQ8yYh7xWUBez4hAcWqQpUQ2ClWDsAm5RSWCi5TJiimMI/3EkdnNDikS2D63zXC7wd/0ZPOAvdkyfK9BXUj8+8a3xLZHEDGjLBWNiYCOVCyGiPKaXEiE1BuJlwJQTjK7WaSNvQoMxw595DFO0D0V6J4KiKlGfcykcepvNmTbOV4nwo+QHowgqjSmfWBhFWPKmfqWYrBvZ+z+wJaUB82nSHQ39Br8EenkCCLNOr0JUIHXHlcE5NWUVbOx4O9GzLHCDArTrS/MUiB8soEN6w1sS5+qeilSYsNWluZ1hcDlEVcEejUgXyiIBOQKuuuBfhYYpKUe9VjtaCeWYeoQz2riY2Hf8VnFMAs4HJ4EVgQTcbh0P7HJ8sTvDywPlimR4NEKTKQ8MYz3C6Y3c6a3CrbfKdj9ckn5q4Gt9wrydyX5ypCfaoqj5A0mTjzCCvz9HkcgHruN9qTqM/TtSH6gMDcg3rfUr8+xywHbO6RRyUqm9Yyvz4ga3DTgPiDRn05thnutORvbrEdL9cueGANVVWJbSyxSml+5N6IY58hMMfQD7bxmdbik2V9hT3viyhMPPLKOyJuBipI4PMJyi5HuJbDa0muL1Q6IFO9pRmqEuZIsgEIpMMcSOcgNgo0/L+i2HMP5yBAscqbx3mO+4DFvR8QyEmuHaAJ+5ZJgIqQRm5SKKh9RlDn9jZrHq0XYBrOVU37PLDEAd8b4V2tYJygOdY9rLdrplHulJL4UDw9PlEC0EeMVIYsoozeuO1FA2BLEqcReTNZCeqqRqzR6Ur/eEzVrPEUgfmzEsOihEMQ8FT1syl5Cg9QCFA/jd74dkPXtw1jWVTjKdDIoo9KJAUQRUvkXabbli4CXEeeSakfumrMqsKYJ5jcl2imEBDUXcDkBIdEk1ZH3qYL67cRYykaKKMCcI8HvFcQxOO0Rlw3kCb22LyV7WXldQJdkdaKHsJvYMiKKJ9p4uZfRbbdop8hCTggyzY5tqvhBJ1NxHMjzOt3RHjsO9alAH6ZqIBSYpcGfDLDMqe4aQtNTWIVdKFgEZBTowpCNInEqETjExqxQUOct02sFjkhW5OibCuYt7nhAlxprLcFGhNQcHxxyerSCRmJ/oEDvZYR3e/L3BMOsR+0aMAIkqPM5i705w9dqdtUWbmVRpcIfO3wIFEVB51tiTLI6XSYxPaUgbIGNjm7iEPNkUCi21xUiQDwvkXcVwVrUlYR5iK8P1NqRH2tEA70ccPsWN4uol6uHrWjYIVFFo2SoHFLmyJsWk+fosUK3EjPWhKN0MGAj0URcbXHBok4sIku8g8e50CqoxE9wkugF9AKdKeLKghDY31+SDZpiO8OS2E+hjHTaUlZgnUMBffAEqdFGsVEGRMQVHpkJfAacRmgkMohk13QUCbf6ZM30QH78IyPCP6wZrAPhEQMokRw9o0yjzODD2hQ/UXn/WBX40VlwSr9LX5LQIr0RJAaOj8ltoBBYYekOWuQHi40WLspI/qWEJJoTgXQSuUinkjcRV4ZkkiYiMQcdJHEqkvSvSX83uB479tjc091pUM8VDwPNBImpQ5ZOwzhTxIsp+1XItQm9FI9VpUi4KBneb2lthxUuIYQZhIL0ejqdkrJQ6IvlRtxnJB1CqhVkx5L82KBaQb6vKJsMdUiqODVkg8IfW8Qqkf+ll8jS4JU/Yzc9QLY7zer1EzjytDdXyaxv2VPfWzI6P05z3onAOZcq3iTQ/bhJsrfgqf5qw/ieIfz3x/Aoahoi5k9t4bJAbRua0xX0gX5dhZYnS7q25/R4nhISfSR0AeYB2QrkvUD+hQC3LPGWO+uuRIrWGZqOXgxrRhzko4JpNmFcjDBSUYWC0uXEf9GdofkChFbJKP12wBXpiqK+6Oi+umB1a4mdD/SLLvmNSUEYwlr6GmFP0u94uqlDPps/4bYw2AEffSJm3O1BQVlV8NWB8NXkiZbLPIXfBZEA0rqHLEW3hN6jjCY0IU1aHhtTSS9RNwP0ye9K9QKRScI4eZYXz4+IX+83/qHwwHfltH1Dnw84Exh6S7/o6ZuB+b0Thn6g6/pvm9Lw7SvwAzrlA9K8W4dnx4h0iYHVTxzDdiCsPM3BCv0jkw1/dSKog6TQUPNkyZrmwAkIilkyBw/r4bmfQnunwWYDOhqcdoSZxB84MhdxymOdRe6kBeT+7jHcc5TXxsipoVhqQhlxX6wxL48ZLgeM1Aza01Yt6oVy/ZlAPp3RbNdktaHbsaggiR0Esz5MYmJz5e9kaBmxjz1AOwt0OLYOMnSbUgL9PJCrjHDqkF1EapCDwp8OZFuGvusRXhHeGMgOoBm5DeeLGCLj75ghb67v1Yc90UfK8yOObh6iRpp+v2bvk5d5/Ze/gvzMmPGnLkCIFP/RknMvXmR1d8X0uW0O/t13Gf8vz5wBLwH8ny6o/1ZLOVb4waNKhd23OJ9I9A/yoU4PT8kmOXmVIxyYIktOj1nA/l8n6I+MU28uEmd98doJ8rKhyCaE/YFwy1Mf9RTLDDFE4nmF3DYUWcVwMiC39dlt9aOG+S+eYH56L121hKK8WmFOBOI0kUaGey1ypAkLR9gVhJgYdfqdNBNOnNVHu6RI1irKXtMbS2cduo2oHtRUMPyvJ2QfqMh9RZhGYptAx+GgxywElCmkz1iFWkakldhoUWv9bIzgvMc7YEibOQ4hiXtqiRoibh1HmwwYxNmYdQdGpsKXFr0rUAri8GBvRLRJtlZD3+Otx4c0AXrc9P2bc6E3+u9UKWM4s5QRKsVA+AyGccANIYU5vVQgqs2XlUGQ3RZJapZH9K2ILzzRJX2r1z7dyXTEDx573HNSLKhdwzANiSB/URHyBJjJTCJeyCBGzNsekQvMD09RQsOl1Er7p9fp8NdTSoQ5UVBEzB94wiNAlBACntHYsU8GLBNF0OAyj5xqXBEIAfJZQfXilMjmF+jGkfGqIK4CYrGursuI8RpxEpBLiCeBeGQJXSCKiBmZ1NLtQWdsSrh45Ih206Qntfs9i88f0tc9y/tz5DrxfnCWrun4yv/8+4SLktH/+DQCQfdzt7nS7FF//oT8hqS8pZG/1eLf7Tbmr+YTU+q9npM3Djg5OiEaKKclIvIw/+gBD95bz/L+gnjo0KeQd5pxrNj6xDn8af/IxCaS/dQ2+pNjIoGqySlnFWPGFNZgokEfgTqBia4w+5sjNnW1IJQgS01oPMVtRR40I19SDAaDZrQ1opiVSC0Jy0S0UZVm6CxVnxNW7glGf2wj7nhIDpAxJm56BFPlaKNT2NyOwY8g7KQrgbxqED+3mzgPGbje4URI9GC/CXIrJRMJI0vGeWIQhEqQ1UnILxuB8XpT0yBAlBIzzlIg+tigxxo9TZ3AeG9CNR0xmo6SpLDMU+DcN7gPP0FdEUokt//MkGcJQU6bOcmv5JZOLJVSYqPD7nhc4XH32uR9+0yxSSQQkH89qSr08br9VsCQDohhmgCJjJQukF0u6LqO/Ee20P/eHvJ8Sm+LlUTsKYYLkcXvHmFeGaVFc0civUIfCcRxwNQKcRzQRwKWAf1ewJxIzBzEMeidHHW4ycxSnxijzieDeVsFxPlksOfGHoeH85KTNw64+yvvPzx9H7a7tWToe8gF2UomkCqCP+rxJ5Zw6Bjeqglzh9zSeEJ6zSOHax1FlT1BlZN3Au3vnCB8ZOvSNipTqGnGar6gntfYZY/VnvIzO4z/5rOITDL85imz389p7q7QXiEzhTj2TJ6aEX72bnqPB9ZePlD9J5fhwwXzd444vnuM3s4Z7Y3T3Yu4jpmJzO+eJDJCkzJtjUsMMCkk7ovNBtlHXs0T6SEEJq8ZskOJHCA6CAcOlgGzENiDHv/VZmONECPmx6ZEIvk7AlNLYhOwy4GhGfBzRzdvE4FoqpClwkqfaJHTyDJrYRmfEJtktURv51BHvPbEZSCcerIjiXISZVTa2JcUIhf4PVDfNybKiHtFw0zRMRD7QH20Sp7j8WyWHNuQrl0+2dsypHFoGr2CGAKxjd9QLGTLSLA+AcAioeYPyFDiQVjfQzrzN85Mkk8IKON6/utTm4oQKUPXBaSRUIkUv5GBzFLMhrOW1dfnmB/fFOgjQd0NSU6ITJI5HfFFxNUDUUO3Y/GjSHNpoCuTJah4LkvV0Aj6yqXqOBGIZxOqnV0rEMVa/SElHDqyA0FsPeoEOAlIK7CnFnU3og+SZQnLkAjxJ+Hsk4uk4Ty+eYwNAzYOuAvggyOIRDjxlyBe0piLT96x/MJCHxGDYNXV+GFNhq8D2IhvLL52RBGJNhKmydPa7UVUJ2hWj7tIgJt3jD+5h5BJ4NEcrCi2CuS5jPxShTdp1KJ+Zhv9UkWMkeo/q5nsTNCTDHka0x36pqd7a8loOqL/a/fO7qzrMZr5ry6RP5sSBA9ev0fMYOfaXgoen1UgBJPZBGcty3dP8PuWYb9DLAPicz2FzjfuwaKSyG2NnguawxrdSso+w77b0NxZYJc9eNCDQh8LwtxtAIvyekqKyN9IY8h46PCnFtmS6I5R0B21qN0MuWeoZUNuMkQDfjUgLprHFregdi297enqNk0wBkuYO5RX5OdKtNJpfLMODG9ii5gpRBRUVYnaNqirGXpmsJdiur8+umUyENsqcavnEYVIIFuRDhBnEldhQ8CzJpH0b9eIXhAaD6eeuPL42q4PrT791w84m+jL8RtIE5+01FmnwnuXdLOs++6h6XE2hY0Nxx1x6Yj7lvh+T/OHpxR/dnfDiZEIsoZ8mSXSuIPQeEQrEqPrxgAh4kKyXbGFx1uHOxlQH6uSxcixIxQR/6wkjAVxpnDHPfFH1kygWw55LyB7gZyvIfl5IO471EFKKbT7Pfn7ApeFtRYXzG0SLe+RX9lnpsxPTmlLS7iocEWkuxLSaGMr4luLW9onR3JbirAj6IuBpWmwwSEtDEcdvnUoo/DWI6VKbiBdYg95H4g6kl9LyY2PPlu5nWFvt8guUocWbyJd1ycb2EsS8z0T7HVB/rN76R7/Hx6x9fQMvZPRH7VJeH7iCccOEwyTD84wv2Vp/8HRJi5xLcN/Oqf47glbnziHnuX44Jk9v4s0kny7wHqLUooQA3bZpyBzKcnzgv63Tp/0tlQC9aZHH0N73LD/xTvIQmO8ochLZJRkc0k49PA73QaoKEQyThcnAb1MpvnN/SXCQnvYJCO9IXHXuazhKYO/2VNcrtBXS+jDE3Wu7ztaOnrtkg81LlnkIpBXNEJKQhbpxo5eDMS9FKoegXxpsLdaur5LksG7ccPUEEFSwo0FXoe0L4sUceu2IjY6vPIM0q0jcB+J6z1SCGJCny3ExuMWFt+mtIqhGZISqWnpuu5fXtD/oJV2zuF6y9D0tCcr3PFAv+wQnaDtWnzvYFchdjfxsCihfE3AgUMdRPStAHc88q7DHfT4N3viwiPetsx/+R728zWLVw/JPzhCjNKnFSIdKDKXsO+Ic0enhzRDc4GiNpQhw+zmiG49F3zfIRzYL7fp5z7u8HOXZtWLkLqLywL3TxdniyeCvJJjrle4a5FBOmLvafIWtwfYgHvJpPHIY6alza0lg7DYccCpNKO1owCVJIRAaDy2HRi6HlNlWG/xk7QIXRZx7zRItVmB2zb5JM1vHic55VgQP5LRLzr4eEG7NVD951fTvPdvHLFzMMY9I8k+NKY/6mgOa+y8Z3l3zs7ze8y/eMi5T12h/GxIRIRwtonL/+IpFvMF+gMlcSbRVzKihN5YZk/vkk9LhJaYMkOUiu52k7ylp4rtZ3fxb7UbCzMA6j2PxdK9X6eo0SYwxIHYBZo3k6Z5+9kZ+W5BtH7jyhVuD7jaorwkG5UYNIFAca7EdZbi5Uk6xJuAt455vmLoBxb7p0m08tiv5qShdS1hC+RUpbSILo0huWKgEoQrEhkkTnrMJyYPn8MgBrwOyQSidlg7PCRbnE2REhakakHYW8sDu0i368iCpmryZED4uPvrux4tTSpuA8SBpG136a7uncNZh7X2j6FGkqCVXqfBm/WAW5Fvl4hRyoJRY01/3uNtJPv09hP4ujkRSC1p79WsXEN7s2Y1rGi+vGS1rFFC0WcuVeWrhuGDAvNjE1Yvp6wkAFkLzNc87rdW9F9ZMUiL/OCa2XXk6V+dYw8GxH5g9TvHZCYj7nvEjibes6AESmnCwYCuJe4PavzhQLhtkZezzXbfR+xz65CprZ5Gdrhd6EcDTTbQrmp8Hp4AsYbcYZVD7miGkae74mlDR1PX2OCIPqJyTV6kSJL63oqlq7HPCYaZpzE98tliw/qnG1r0VoZ+umCxXNB/MGJbi/1eQ71Ykf/HFxGVwn+u5mI4R/guw/iVbW7+/TcoZgW2s3SrDhEkvnb43iXg7IWc/r+5l5hMDz93oPz5Z1jkNb0Z0C+O6K54yutTOnq2X9glFjHZvBx0KYvqVos6TK1j/3+ebPgixfmQtNhWcuHly2RlRntcY7TBn1omozFGZdj3O+K7lnBzOLubKyhuKLJWY086Tt86pFv1uCYFp4s8gXj9fkf3xpIMg/1ISgd0+wPqWvbEnD6aiHyuwFzIiSIQ+oDaMvg7Pf54wF4Cd2JZfv4I9ZPTh2siElkcLZBjRX6qUyBeACU3t0zwgfB+T3ZLoPYj2dsS815E3oz4GFhdGNDnsg0nEz+3qK84VANqnu7RUiV+gJBpdKq04dvaUX+zMZKSyURLKZWyeoXAVBkyVzBSRBvQ10tCv0D9xIjHzS/D3BH3BZEMVSm0VLTfHzBmm/H9nLlekL1bEjTEc5LquRn1UwOmUBt9vj3uae8sUCuBuTwivKhRewl9VjND86vHLGdHqBdK1IWAHhlOv7rP1p+6RPO1Bd3+kuzjOUd/eEyRbWONx5sBt+/Qz6V56qMaWv18xSBa+l+4T/y9FvWVU7xzUArMn56d3fHFGclFfKyg+QennP7qbcSOovvtU7Z/+CJb/Qh5P2DjwHDUo6cG6xyjq2P6E8viykDYt8jvrRC5eORBReQrBfPPzxNB5gcU/R8co76zIj6tKP/y1eQKEYFF4HDnlKoaEbOO7HqFv5mE6Nkkp9guyV4Yce78hOZjIIcM2gfMiweDTJAXDPzcHu1f38e2Nc4PbFfbVHOD7SyhCYzOTfDWEReOMHKEE4H95x3VB0cJWFoLFLLXwPSK7FRx9O49iqKg2EnuKfaoZ1AWrCC7bvBO0N8fEM+JNecgkLWaqtDocUnYKgnSoaqUO7x/ckDx+w2ikKjLGQefvU+lZsxHAf+SRl3JHnMjjZifnDH81QPCPYe5UqToEpGjnq5w9wa6uyvUp8eoF6ap84tnldWuBlzTIyTY4wH/6QJRio3NGCtYjTvEqz3eZ9z9pXeYfeYiEYP7iQL3tNxwZAkrT/F/O4a3e/TKI1uF6CAuk1Ir2IDrHfJxzsIfJZnh8XgVkxkm2xNsb5k9d47sfE4sSJGIH8g5Hi8QP7eLMInYcea1GokP9AsPfogQ0/zYxZQJkyfecCzWTvvhDJEUa6tU/1sruKjRT+WoQTGUDiHXrykF8YZF7WrE65b2v71LttQIH8mfGXPy6j3yj04Ip44LP/Y0/Z6jnnSET+SQpfDtb/mtCEH/dw/I//VdhDZE/GbF5myumoAcSXCe4pcHwv82Z6ecJUd+neHaAVFJ7Ciw6JbI76mYb62o/tLFs/n6Y1JOoQXt/3GI+c4Kec4gdnS6m7n4sG8SUuBv9YTOI36lYfcPS9yXGkLrsU2PuVDin5d0H4DuWY9+ocJ8bPQEceTsPSXuVke8a4m/0XBtOI/7fI1qFN3+Cu8iZiujfGZMazoWoSZ+ssD+eIa6mIGE/B9Zyrkhv60wrWR4oyHsW+gCTduQ75VUH95meanHKstS1ui/fB58RO9D/r+n5IzyNIM7CQDsTztWd0+Z/vhF1P2YOr+Lkps3byCfycl+Yhv5Qp5GPIINsQE+JsngFxribfcQocauBwAAIABJREFUeXZZiiNVH69SeoMNG99LlJH4c4f4D0myqxXxKUV8Pksg1mPuKmgJi0B5qFi8M8fkBvF8Trx0timiD8S3B7IDgfiaJb8nKW8ohBWIZcTd75FC0B231Cc1wQdWp8tvm1L4TdMJH/jU2sEx9D22GQhLjxYKP7iU0HApw/9ontIHzphlifMZ1hszrtMJongYiiHlwz8l9kvg4WsIkQimQgrKX3KYj4zSLNaEdAAg1q+fiCFRAtcylv/WWynOsh1QE4NvHMPthv5Gi7aScJxCyOS/sbWep4kHM/XNn/3BRU4qxF85RP7MdtKxhm8eCyPW7iECqF894qXveyUFOM8jvnP4NXl/UJbx9e3/r703+bEsu+/8Pme445tizDmLNZBFUqJIkdZswRDU6EYDbnjhhRc24L29N+CG/V947YUN2wvD6EX3ot1oy3JTrYkiRRZVIllzZlZkjG9+dz6TFycyikVRZBXVdMtS/DaJTCAz8t13f+f8hu8Av5Tg9kF+MY+J88MYhJvyI6AfZchEImbqIxjei0Pjeo0hxwpZaNLDHPH1jrCyXL1zTj4rmH3hkPQwp61axH9Uknx1hEjETYsiwg995uuKQpYSdTelmI2wf7xD1oLR/pj6ZIdtDUmR4GWgdwPpUUHXddjcoz5fQA/j72vkiUddBMK5RTUClWt86xGJYPp4H7vs0YcpNjj8awkmGOShJnk7kO8S5HPPcNlgr3q01rja4EWg/WCHbS3GW4ZvbBn+2zHZ7+59xLwKH014X/waXIhbgiONfCWF1xJ4JUE8ip7L4kUS3risxAM1OM/0qsD9ZyXikSaM5fWzEh81nv76Z1wPRO0kRPLLo4QwkgTj8W91+NMB+Sc9WZaS5hnhnZ7cZCRbCW1AWMFwFcX/bGdpNhUhwND3P3Z19ImQWMEHnHexQVeKYCFJk2gsNUnhQKHecoT/bs34SweElyTmbtyDTRcF7R+vUb89QnyjjwbJPsGedYQTR3IFw51AsUvwv5WRPxjR5B15n1F92TG6SimahAvVE/73FvvmFrmnWXcbxGcS1P2M4t4I88/WOOnxS4P47RI3N0ihaE52qKME+1aDfb+lOdhx8OAu42zE9r/fkLxWYF9TFGWGSpMoMHdXI5467N3Ie1ZPLeY/3Cf8zw3yQYq6kxEu4+GgE02/65HjOPzovr1l9rUjmnxg1uyzeO+ScZ+yqbq4TspgdK+kmjekxiO+bZmOEtTGIw8TVA9MFM46QuPxeOSVR89SaD2h8xjlUPfSiMzSgSIvMKnF7iz+D2v8kwHVSQyCcjbCtY7+nZqCCYcP9uj/NFAyYrvYIDaBzCSIiUSUCr91uMOovSwyyfC8IX84Jv/aHdJRYP31S+qrHdk0JxiP21lkADXSaKWZzCfs/tcto6uE1b9ZcPyPHjP2I5rFhjB4+nlDu+lQmcLVBveSQLoAnUcLRbHJqf/pJe1bHbsPOo6/dJ9JNiJoj2kMznryaY4znuI3ZrSrhvWTBdk/HZgeCPp/oOFRAvkLhVNLWHuat7f4c0P9P5zGKnEs2fvtO+x/9Zjz/+MJ3XnDwX/zMtxR6M/kiESigiRcOOSJJXzPkP0xqHWg2u4o/8kREzml+mp0LfTCs/nfzqI9yhuWzbMVIYfP/Mev0/sB9UsFFJrhKwp5D3SaomuJSjIUCinBdRFerMsEsxsINrY3xgxR+eZvYvD9Am6S5SnlqCDfL9CzFLWnCY806irQ/5OEnMi9NQ8FehGQBwnmaY34hSLimbXAP1TYlyXJl0rSLsF9UeErS5Jl9F8W+KlATCT9sUMlit3dnuQK2rIn/9qU8EpC+IzCtx53ZfAbQ5Jouuc1ye9O6f/5Enmc4N7rsIuB4UmDvxzAQfGlKQ+/8hJt3dDbgfxegbybkD4R5FlOaB2z1YhmXlPkUQmxfEdhjcOf9ExempFcRo2j7H2B3Rm0VRQ+h9ZTTErcOx16P2H2ygEX/+P7HDw6xF4N2N6SjjPaRR01n2qL6iVaKWgCmUmRG0iNRp8Gkl6Rdwm0gsxq7NsdeppSNClJSFCNIP0wiguqFfhvt3R/WZGiMectrooTdOcDxgy08wYz77HznrJJOZT7lCLHiUD+nkDOo5JK8d41s6dKSWc59psVI5cjNrB9tkJnmmHTk0wz+rYjv1/irGP6aAaFYPi/NqQhZfpwj+0/P2f97oJyNEJbRTtvEFKQjjNca0l0CoWk33Poexn5VuHnljvHdzg4PmD1h+dc/eCS3dmW0Plrlk6ksHZDT7ts4K7m8Mt38V9KSH55TKo04XMputDouxnlaIQ80oj7GjcKiJFGP8rIf2cP7RVDN6D+y332f+cuxcGIUpTwQDPKS+xmID2TdPOWJEtQCPR/sY/61THhgWS0ybCPIL9KEJWnGI24+x884PKPnjP+xT0mj6Z0Xwwkr49IXi5IDzL8RJCsBFmtCQsbQU3zEGcKvce3Lla2xtNWzc3u92+cwFJJilGJThOKwxF6P4v9WC6jGsJrmuK5IryW4qUn2UXxd792JLOE9Exg9yMsL5sWODzZHznkL+RsLzYcXkwYvkBkBHUKeepJiOwVUzjCpYt60M+hP2npvrlBzFS8iR5r2t9bYd5uYeUiQ6cNuMsBuZ8QOo+6n9KfNxRJQXqQ0723Ixvn6ESjJ5F8oFxkjuiRprc9IwraviPvEuzbHcmvjJFvDIhXU8IfdpSvT+CZRU8Skk4hRpLwZk8eMuQqULwyRjy1hNZTPd/clHKpSAgSfOcofIYyAtpAOSnwJ4ZUpshLR1IpEqWi39BhSTizUUD/ez3pcU4iFEmv8d9v2b69JJMpbmHQKmH14YLVxQpvHVmWM9ofkU+iKd3ky4cUTcrm+ZrJJoOlJ7WadCVJxwniuUNJRVpp8nHB+vfPSVVKWZaYbRRz66qW4mhEsp+jcx3FAt6qojOFV4T3BvLDgiykzL91xvy9S0b3JvjBIUxATxL0QUo7HlCPMtIsIXyrJ+8TwqVj93zDdG/G0UvHhI0jn+Usn8wppwV6kiGPFN55jqfH7M429K/BXjLF4phsCxDR0scuBuT3DXIlCIPHjwLyMMH8URXJEFOB/GzG2JeI/YSsU5ixRw0Sa1z0LTJRvLE4LBG/M0KUEldA0ST4UqDftPC7JeUPJMXRiOP/9DOs//yKg88dM/x2gkTQf+7aqeRDjzPR6MA+60jPJPQeX1tC57DXThxusAz9wNAPP3F99IkTOIQIqxPEElppjZxpQh3wjxXqWnZVfa0gVJ6iSgiZQFXXU8ClQBQStYIyFIiVR115ln9ygboEeV+T9ynmy4Jsm+B/vybfL8irhPZzjvRNDxNBehb3qrtvLhEKpJdwZen+2QIxkcz+q8d0/2rB6Gv79O/V0SB7425KxEwk7H3tDnqcYmtDGAvyWUn4YCCxGmaKrNO4P20oDkZgA/qtKLYuLzxSSIqzhPCyQl9COS5xZwOFKggLhxwEWZbhC8hPNNXljqxPaDYNw7IlOI9E0q0b1CCgD9HqY+dRnWS47Mh2saNxcwMLRzLKsFcDcndNt7OgNgF2gbC0mFVPUiua8x3D9d7YGUeSRukW51yUykWQpCnlbISYSeR7LvorX7q4MWgdYRkZNZxHyKPyEuUkq3fmJDqhX3dU8y3Zfsn4zgTjDNPDGWHjGN6pSEYpshNor3DPB/qrltHhGFMPbJ+vIURcQfa4RMwUtrPoUYq8ArcYSBpF/XSLuxy4fOcMiSLJEnbnW7JRRvnSlKvvnDJ6ZRqHVYcSlWrCyUDyxRGJSLB2QEmF6mKFUn+wxfzhjvBQ0r9bI5Vk+LMd5qKn/K/vkqYpqUlJ5oEkSXAykDUa91Ybfb0ah+sd01f3UStQ+wnZpUIkAp9D/c0l4eWE6vkWdeoZHgbE24b09QJeiXK3aqbJthrXuDhAqwT2pCeby4iNtwG3i4M6ZyOYyTvP0A0/Fnn16Uvo61tYJ5okT9G5Ro410gSEUrirgVSnyOMEdeGRE033tCY9ynDPBvTDjGwhkVtBNkqxlz1SK+Z/8JzReIQ4iB8w7ClUrihIGe4F/EHUIuJ7fRQNyKD8pT0u/uXTKPWpRTRhPtCoo4T2XyzQ0wzzfoPvPW4ZLU3c0iBMhLxNRhNC4+hWLaPRGCUkupGkRYRuSiFxK4u/K8hajV30CCfwV5b8N/bRFwGvA+HUIIcotqaIptelyKm+u2JUjJB7msXXz8jyHGkF85M5Qzfg+ogAMoMlmECoPb53+M5TTApMMxAuozKG3VnEOnJFpReYdcTj+p2jP29pLnZoI+muGhgCm/M1wQessfR9fy1SHyVksyxFSInbGkpf0K1aMqHxMtCe1PGzVAFhAtIJVK4YPmwRXoKF7dmavurQRUJW5Bg7MJ3O8AqW783JywI2Dns24LeGYTuQ5hmL9y5J84wsT/HWIbQgFSkokEeaQheE2mFPOs6+/ow8ySARjJOSYdNjB0tbt2STHLvu2fvlYzye7mmNeyzxa8v+L99BFhLhBLnJ8MEj15HVlpJS9TX5VlP98RKRC5SIFio+ePI7RYSoLkApjUSQ2wxz0iKfOMxJy/QLBxGJdgh6LyV5P1JQZS8YflCTzDKUlcjvW8yBJ7/S9I89WVlQjHPybYKZRAy4HmRU+LgKsPHQR4EC1ziGpsf0huAjVbJru08kqfOJEjhJkgjqKFKSXKP3UkIXQftt21DeGcNUktmEfupQW9CTBBYOUUTARrAOdc371I2k+MqUnAzTDaS1RgWJf1WRrhVmFsjmiuJcsQ0VSZYiEYzPM07/7fuEH/QkL5dMv3aInqYM77TQRHxz6Bx7XznGnLdMf+WI/jQqUwx9z/GD40jCsAPTR3t0akA8s2SPx9H9LtEwk6h3HNkoo2lb0ueB7cmGo+k+Td1SliXNdzZM7s2wrUX0kGUpdmdIrMKtI3xy/3if0z99Fm81oFrvcMaS5Tl9E6f6Q90jLLjOYneRymg6g1lF8EK7ahAW+lWH7x3NvMI3jq5usduBZl1z/sEpaZbRVPGG6dv+GsnjGLqBtm7YLDbQeezgyJJo2r77cEt32sQyzQaaZcOwjiuL4aoHG7j6wRlKKmxvML1BKokLjsl4glSKzfMVqhcMmx7fOHSmaS5qgg+sn68QUjD0hs1yjZKa0d6IdJLjy4B+mFOMcpZ/cE5Gwngyodu27J5uOXh0SLdu6OtosVmMC3SmcOqalzxViHNHVqaMvrCH31rkfoLeCNyBQH3oqb6zRBea5skW96yL+sp1ZC+JV1KCDeRpzuzuHuNkBHuKzcmKsiwQTy02xLK2SAr0RCMep2SLSHIRM4WoAv7Ssbcd0f7Biju/cJ9BO+SJQR1nJDrBPhAoH61sRSJRy4BbGZKreLGEPmAXPd5aTGfom+4jMb6fsj76VAkciFxGrRVSSHSRELwnOcxpip7is2P0CvjFDHc1MCunGGuRS0/IZXRE7wRZpyJR/sQTdpbNByvkM4f8zRElBe6xQFuF3grkEnQraUuDXgSKPqU5qdCvlVTfWqJyjdpL0YtA950No988oPnmmuwop3tWYytDfxaJAjKVhNaTjCPjpl90iMqTq4xkkmFPewQKlSoyn9B+sCMvi9jznPWkacLmgzWjozFcOvJfndD82YrJdEq7rNFWIVuQffQQlr3AdhaziX483bql7zq6rr/WYIkWrlonNLuaoRrwg6ffdAy7DpkotmdrpJCsni+i4VVjGNooOn55csHQRrB7kiTsttvoNjGYH4vcie52oIXGNobusiWEQLtt8IOlrwaGqoMA7arB7DrmH14xO95j8XyBaQeU1gQCo/EI0xj6vqNZ1oTek2QJwyYKDpjeYHvLbrNFa03f9YzGI3SmSJOE5ChHHmhmezMW37xA9xHz7DvH7nSND55u2eCtZxgitHByPMU5TzEuWG3ijr1ftIx//RCdK0QNI58zCEvuE9qnFbhA23aEZ4ZhM+CEJ1QetxiQ91PUl0sO9w5I85T57z9n/No+6txFYMtZoF93kAr000DxmTHilRT1LYv9qoYkYN7t6EWPMhI2Lg73xoZwakm+WCBThTsSUZjiux1qP8GtDPbNBtFH2qnfGfrdgKkj5xcRJ+hD/8km0J84gQmRzqSEQicJOo8oDTXV+Noh7iToMyLssvaEKpZ+w3pAP0rJs5LsvYC3nvygoH1nh33S4/cEYu5JZTQts8878nWCOwBZSrrcUmwTuqcV4ijBNAO5yJj/wSnlozF+axh9eZ/tNxZMvnIABOzckBYpvndkd4poRzrSuMbQ7zoefeExpLBb7Ej3MrI8o3/ekDpFmqfRBX5hCHuCfKGpFzvkJmA3hulXjmi/v4Erh6kMidLoIn4xohF44xhOO4QW5KOCUV7y5BvvRTTbtft73/XoRONdwPQDQgiqXUVXt0ghGbqBarEjHxds5xvSLGV5tYw6085jr79gMxiGYaDv+o96pfATVoLOYfuBrCxQWnL+/imzoxnVqqLe1jfl6tDFl0dKyfJ8HsXGjcE7z3g8ptk2yFTGkr0P6EzTLhqctdS7BiUlm+WavMgZ+gEpIuNqsj+NMwcNoztj7KWhnzdopzj//inVYkeza7n/0gM28w3eOdqmZXowjdavhcY6S9Yn9DOLfJQxTcd4Afl+QVd1JGPN7g/mcKAw857N750zem1K07fgYq/tTgf8wqL3E/yZ4e6XHlDcGXPyl0/Zz/ewa0OoHf37FUWZ4y4Gyt88IBGa5qFh+l6KHwvcn1cUR2PqN1dMjqbUXY3vLOLUo79YoEpN6jR5lWASi9pEC5awcLCOQzKzHTDNQFd18UJMU7qmo21aPml8sgSG2E8Bk6MJMtfR6MsGklPBcM+TLTR6P05ZhQG5pwkLQyoS5BMDM0llG8q9EX4C4rs9018/on1eo5YB8XKGGmkSr+DCEUYStYDwssa81WCOodhGYvT8T09hrCIIZOOhDdh1T/6wpHu7ir1gbTCbITq9bQeEkgTpEQbyrMBsekbHcRiTdor8sKR7VqEf5qSzjPpfL8hfGUWbi2d1VPO/MiTHOUmnSe7lbL47J3E69lMHBcN5S1Km1M822NWAJ1DujWiWNfWmjsgp527sIl9QxJTW9H1P13ax37pG4WRFxma1IU1TjDEMXY9U6oZ0/zHE0U+VNrs2kA6Cehuf0Xa5jQk6RAvLvMjiYdLEgUrfDxRlib22uNyuNowmI5bni7geKzLqVYUdDPWmphgVbDdb0jSl7/obUcTxNM4b8uOS/KhAVrC72NCc1syfXlCOR6gsKj56Ex0JXtAsJ4cTul0XyRTy2mCugREF+ZcmhJ1DWsi6BCs8trG0pzVFktEsGoZ5S/9BFQd1Q8C3juw/PyQZZ0w+v8/iX59y7/MPOHn3hPt37tNftAgZn5V91rP/D+8jfEBvINxVURsawfCNHbPXDjj/F095+AuPCUeS5JsOVSboLxT4swG1l8KVBSmwlUE3MjLFLg2h9TQXEZiiEkW9rWKL2bQ45z5xAks+RTjn6OqOYdUSOo9dG/TrRVSK0MT+Ioti2ChI0xT/vCcMATFSFAuF2HrSpWI7VDz9n75PX3fRaOwHHXqSRl5lc+27OkkRzy0ZKckTj0qjaxwI+nd2ZIc55f0xd/7xY/r3G9b/8pz8s2OEFNz/9Zdi/16mH73AbXRbCMaT5Rn1D9aoedT52pysUbVAbWMJJY7isKMgR8yi383ld88os4LVe3PcYkBnCbYyyEFSP98hlYqc14HIoa4Mdhd30VmRI4T86Ea8LpHiDeqjH64PVNuKvo+36nqxxjtP18fyNs1Suqal7/ooOconS94fTuK6rmnqJpa9fc8wmCgmHgKb1fZG0nQYBtI0pd5WSBlBJlmeMT+/wgyGJNV0dYsPnqZqSNKEzXJz83elikL/SkmssaSTHDtYEqGpFxX9VUOiFMEEml3N/Nkls/0Z68WarokKIipVCC/QuUanmmq+I00ztmdrkrs54fRasqgODM2A31mYSsSpY/3hivJ4FPfiBsxpj3Cgv1TiP+ip/pdzJo9mTF7dY322wrxZoVCoDoYf1JgnLcXDMeUklsMeSD8UkU64dTjpWJ0uefyfvMrVn5/S+YH+rCEcRx3sZCdRA/idI6li4trznrC00by8MnF+0/bRG1mqeCh/yvjEN7D3L0yZIlG9OBwRBoeaJfHmOcyiadY6ILSkfnvD6PGE+v0dxRcmyHVAVOCHAAkUs4J0kjOdRZC8ezqQHmWol7O4BlhZ5FMLJw7769e+sGOJPxnIPjti8+YCWSr0KIFLx/ZkxdFX7rN684ryzojlm5dIJTGtQeUqmlMD28stx3eP8TrQLGvKR1OEFZiLnuLuiP7D5iahtu+vKMYF3gfMeiDJErZPV8xeOaB+Z0P+YMTqvSu0i46JQkvaywrnPLvna7z1pFmKGQZM19/cwC/2e8FH6VBr7DWCL9w8a67hmTeKniF87GT+JCuGvw7nHXxguPbgkUIw9EP0SJbiY9A9H/zNofGinw0+kKZR49jaqKGlE83QDzcbi/BCRy3Eyq0cl2itGB1PscueoR3oVh3L8wVCRnE+pRTGDFEaqI0euXsH+/jgKUYFbV2TkrJerrn/a48pD0e4zpKOCux8QD/OaN/cYpoBs+5Zfu8SvzT0fQ9phEHaeY98EDcmsy8f0r9d4y8NgzYc+D1kJpEV2NrgvKPIckQQpMc5bmtQS6KqykmPnGjMtyvkLlAmJV4H3NmA/GpB2mnSo5xkqzAzD3NHmmjczsHaR0ruusMNUdt86HqSNB6owE8VsvvZbuBrvaQXrBOZKYILDBctYWFRqcKfDST7Gb53TGfT6FKQpPiVo35WIccavzIkUkUf4dXA+V8+Z/5nZ+RfneDfHRhWcXVD5aJG0SNF9lwxvFkhNh4vA3dfuhexp1cD9XfX5AcF+184IrSOg6/eYffummwvj/QsBG7wUQX/+gW+fHZB2DqkE3RPK9ptS5Jp/M7SzhuySY5bWcxqwOeCcGlIDlKCcdSLCm0VXgf65zVSSHaLLd28pVs15Hslth3ijbHcsbvaxqpBSHbrXUxaKf5KInr3ced37z0/j3ghV/ri535MZfOHgANKq5t1hvihkl0nmr4bPhqaQeSshoDS6mMHQF7kN+1CulcwrDo2qy3rk9jTR+FyQVd3TPen9G1sI3Si0Uka1TNMPCjs1pEcZCRZgnnWEjYW0UbpInmUoFYwP7ti9cYl5b0xogcX4p7V1zbaxx7HMjy81eOuDP06iiV8+H9/wMMvPsYtDEM1UD3ZMH28z7DuIqahieg7+TCFXNA+qbDTQH5Q4HeOIbf4D4fo7jDOcE973Gdirri/aJG5wHWxBfNbi6kNQgjWz1coFQ31mqpmGIZP/X1+qhK673tEADMY+suaYTcgnSSZpfGBbS3SRCFs7RXdeUNSJvjeMfvMHv7MRNmbEL1pw8Zy97ceMzmesX1jweAG+n+1xlcWoRXy2ltHnFnkccLgLXlIqc92jF+a4SqDqQa2318we7DH5bdPkTvIDovIw03VtUWpuFFEEAi6qmWoo/ri8t0rdBdJEdXJlvJgxPov5wTvmb10wMW/eUZ5f4w01wbTSvPG//ktRuOS1dMF5cGI7eWGoe7ply3bsw1pmbG8WICH7XJDta1QSsV9KdGG9W9LRD8e+WP//EcPGXldDv9wsr+4aX/czdG1HUVZkJUZvrUMu5Z+02IGQ1PXNFVD33aMJmOWV8ubw80ai9YyiqgTGOoemQjqyx3KCPZeP7z5f9vK4C57nnz9Pe589QFlUvLk997mzpceEFJwVWQ0dWct7mpACYW56MleLdn9yZJskrF3Zx/ro2CE6y3ZnZLqjRV7nz0iQWHebsheKlEViFXALyxH/R6L71xSFiVhTzGctngN6TNBdlig3wl4GdCFxtsAO09o3fU720fppN6wXq5u3g2t9KdO4k9cQt8Ms7QmLVJCgOKoxNuAOe8wWSAbNCKVyOGF21+KW1hYONzSEl5RuNaSVhonPOsfLAiDi7vL1pNPCmaf3ccFh+hBFVFa0yqPshJz3qL2E8LSUp/tqK8q9j97hAiS5ryK/M3asPeVI7qLln4XCeje+Gjl4eKbZnrD7HCGUHFyrLSKAy8RSLOUer6jnI7YPl1hXQRdmPWAw9GsGkaTEc44VJ7QzhuSUcb8+WWkSSp5LQgH1XYXD7su2lfKa+qgseYTWUf+fxWftBz/tGW71hqlFUVR0Dc9Td1QbSuGIZbKSiucc5FxZCNx5sUtP5qMqDY7yvGIvuvQWUKzqrn/S48i/W/w0SQ7k2R7BdVmx+nXn5LNclxrmb9ziakHhJa4xuJ7x9E/eohQUL42YfenC4ovTli/s2C/GaPLFJkqdt9f4XuHlIKDX70bB6TWkmQJTBV2MdDOK+yiJ5tkuJ1FvZIxfLtm9MUpOk+wZZzXmG/vSO5mdMsONffYzjEsWkxjGLY9bdtSjkp22x15nuOsuzkgfz4JLGJpl5V5nEJmKaYbGB1PoAgkRUoyjiN/HzyiBpUr+vOW4qUReUgjvSqHNM2wncFVlsNXjjHOsv7zS2a/dAgjgbwKdGd1bPhPO7LfmNL+5Q6ZSMIA+YOS+fcvsJ1FacXkzpTx/QmmGdh9sMb1kZmUlAm2sx/j8goh2C635Donn+RUy7i2wQVWzxYcPDhgc74iLXLSMuPq3XMOXjlic7JGF5qu7pifzjl+cIf11SoKICAxw0AwnmZbM9mfsJlvSLKIQmqbFiXjCyul/Kk0sf/fh4jQ26IsqHYVzsRn8CJJhYjzgKIoaJv2Y4dDkiYMQySrDH2PIMIw9x8fkGc53nq0U9hgUYWmOdmxrbfQBKy01KfVNXfaY6ohChvcKzCDofrGErGno1tiKmlPN/zaP/wtdm1Ff9ZgjEUqwcErx5jakKZRC5tzh8wk9XfXjF6Zcv7/fMjBvQN6M2C3hvakonx1Srpf8N7bAAAPyklEQVSXkfQqVqAM6KCxqz76MzUWX1n6bY/DUm2qWNlISQjxoPi0rdOnvoGFENghOsRl4xzXWXSp6T6syO+X2EtDQhINzzaG/MGI/qxGpQmbb84Z/eKMal0xOhyTioSzN05YPpnTzRsOPn9M/e4WNUvIdRYlX49TEq0jNUwF0sMcZQVubthtdvSrFqFABEk+ybl484zj1+7gbFQ28IN7QTL+8asxJXGto5gW1IuKtIiSPZvnG0aHYxbvX5LvlVRXO9I8Qi77ukOnmuX5gun+DNPHqetqvrruX+OOdzQdsV1ubvpMY+LNa+21q0H4u5u8hGiFI2XEsHddFw8t8dFtnhd5HDL9iF5UXuQRQplnIATFqKDa1pTFiGySRwGDBGQSBRw+fPcZfddzfPeYD7/1hNFkBAWY2iCFoF93mNVAeidHFipa7ljPcNFxMD1gfHeGOW8JItBtW4r9Efn9EjUI0qMcs+xJZykylay+N0fcTRhnI+rTiuylku67G/L9kuLX9ui+vyP7xQnhg4GgA6YxpDqJPOaLjvqqvmYbxXVZ13YURUHXdjfDy59rAgcCUkikloz2x9jWEFxg/HBGkiXRcOvlCcZZsiyj3bVRwfCqYfxgipsPhE3cl9VXFYnQHLx+JyovtFEfKRs0xS9OEUNk7phFTxCBrMxYvnFJPisYmgFpYbfYUkxKmlWNaS1KSpp1xejOhHpeEZxH5wpvPm4ufSPqHgRJkXL1/gX79w/ou57t2Zo7r9zl6oNLitmIoe7ZrbaM96YszxZIrTB9HOC8MDwz/cBkOmW32QKBpm4ieD/PqHf1x4ZIL1Y1f5vK6H+n+SvFjRC5NZZh+KvMGqVUhDeGj1dGWZHTVA2j8Yi26RDEf2P/cI/JwRR3XWK62kZR93WPGVnqtze0vqMcj2l2dURSiUi2Dy5w+Fv3sZ2lfDymfVYjCoFrDa9+/rMMbRdXiU9W5HsFm/eXHDw8JJ3lrL57yfQze4hEYnaGfujQC8n26YqMFP1qwebNBemDktJFCKUWEq8FbmEIScBsBsxFi9kZ2nWD1orVfHUzKAwhYtjj+/hzTmCArMhoqgYtFMko4kpdbzGDJctTzMaQmNi7ijYgA3RXHSqT2NSjxgp/YZCJYne2oTrbEmRgWHc45zn4/DGX3zwlDRrfe7L9DFs7ksOU7rKJpt9ewkixerJgaHqyUSyH0yKlmle0y5rDzx9j2yFilq8fjlDiRl3DGkuaRtqXUCIqZwBpkVNtdmgd2VbVumJ2MGNxPmf/3gHttiZJE5qqiebk164VdVV/7MXsmo6yLOMqpu3+7t64Pwa6+eLmtcb+2M994/Txo1NVEZ0OrLXRXCDPUJki1Sl90xJsIMlTZK7JdMp3v/Edhq2hnJasny6iAgoebLj53u/9yiNssNTvb1FCYzaR7BEEvPr6K7R1S7dskYmguay498WHUQN9CJSPJ5izDj1O2by7IDsasXl3QbE/YrBRMaM7azn+zfuY0578FyaIFVRPNuT7OXYwmNMOszG0i/oa7xxv3hftlLgWyvtZ2qqfaRzatR2zgxmb1TauFeouDhWUjF+c9SQPC3xlkJ3AXf8g6SXFkOLPDMPEUY4Lpo/2MduByeGUcF16bd5bsv/yIa5zcZTvAklQNE+ryEkWClkmiI1n9vI+wQf6uqO63BEUpGVCeTBCpxpTm4/dusF9/KVpm/Y68TSryyVlWbJdbuirjiRLOX96zmhccnV2xdAPrK9WSK1o65a8LDDGUG2rGwc5KWUsma9/zHK+vCkX/77Ei531XzeQkeqvzgCEjGuXF22GFNGxfrveUubFtfSuQGWa3XzL0PQ8/Yv3efC1lxhWLc2mYXI4jaujITYtKlHk45zt5YbqnQ0qUfTzFj1N6ZcNLx0+oqorQusZth31VUW5P2b68l5cne0iA0xPUoL1bN5bIhtPu24QtWf82X12f74km2WErUdPEsJ55IGLscQTcBvLsO4Yqg7TG4SUVNvdjXWRtZZwXZX9LPEzJXDwgbZuo35d1UWqmJJU76/p6pZh2dI/qVEoTGcoipzgAs1FzerdBflxSf+kxvYO0QW89mwvN0z2J2TjjKdvfEB/0TL76nHcs36wiX6tTWQJzb93ge/i7nlaTEGCGzxD11NdbCOccV5x8cYpD772OD6cv+aTxl1m9IMtRyVP33oCLiC15OLknMM7h6yX6whGSJII1r/W7rUmip4LKeiaCIMchgGtP65UtF1v8SEaVv1djxdgkL8OjPDjkvdF0gcfjct/+NeD4wO6psNYh3eOoe7Jyow8z+kzw8m//YDJ4RRrLO22idY93uMGFysqLUknGUFCflhgqwG3GRBI9h8eUp3urnXfBvYeHeAGy/IvLqEL9HWLWxmC9dRPt0xe3uf8jecc3D9k+XyBrQa6qr0elqZ0y6iRvflgSZbnVOdbQh2HZa639HV0iIjMrohuK4oC48ynnj7/jUroF7DKyd4EridowThGRxNUnkSM9DiNHr1asr1YM7kzY3eyYfZgj/pix/jelGZTk01yinHJ9mxNUzfszjccvXSHtm65eOM5o+kYfCCd5phNx+5ii0w1Q92TpCnW20jP6waSIgI32m2HSuIEev10iUo13vi4F3bhx+w87c3t6X1kvVTrmmJUUu+q+LCdvxm4BB99W/uupyiLm4fvbFyJWGNv+psf3qv6a4TXzwuk8bfj+v3JA9CfpDKRpMkNKye4EFc3Icqr2sEymU3ouw4lNU9+8P61x1bA47GtBRFwNjpyBB/NuNO9DCEgPcqp3t+gUoXznv3JHtk4RyjB+sNIPdw8X3H31fvITOM6QzYrGdYd+UHJ/N1LypcmmKuOvurJxwW+c3Sblrv/4BHdezWjexPEEBBThVv0CC8Yth39qqPf9XRNi9SKvu2iaQEhbiaM+5kf98+MKEiSiH2tVzuyIqVveqqrLZuncSG/fbomLVJsayhCnFanRUrfDGQqY/fBGtuYyFpqegSSOy/dJRvFtY5GcfTwDn3fYzpDe1VFs6ggOHr1DuYa7tZc1Bw8PowDpWpg6AzpKMN7H8Eak4jeQUTR9p8E9B/6gSzPWF4u0Yliu97grEMpSX8NSuja7mbcL2QE3YcQosfOdV+tdDxd+at+05EmJvj7F+Kn7JEFN8iuJInfV6KTGwfAF4OfNMsYug59N6O9qBnNxvRVJK0IJcFG1ts1FpR0kjEYw+6ddVT4zKKz4fHdY/qmo102UYPtckcxKuOwdJzR7zrC4OLAdNfTNR3Dhy3VYoe2ktnn9pm/dUE6yxFrCL1HSondGqonG/R+Gq1Ktz3tqmG32l3L5Phr+9YoX2SM+Ru9Dz/zDey9J8lShq5nNJ1QbXdkaUY2ydFp5J1KIZFC0W9bVKkjfarqMa1h/NKMvm0Ju4DvLW3TUi0rRpMR3nquTi6Z7k8ojkfUZzuGuqc4HGErw26+xfYWpSXjwwndomXA4HobF/e9vXFT9IOj2IvILP8TMKbeRfc9YyxaR2B5cu1KUW0qxrMJu82WYlTSt5Gtkxf5zV4zYsXlR6WgFH9vhlafdK30SUtwZx1lWdD3A0mS0DYtOktIUo3SmtOTU2xtyYqMvuuiPr1W0ebnxQpLK6YPZ9HTqxrQqcIPHrPu2T/eJxvndOuGru4wxnDw6JDZ/RnNvIkKLjompS5Szr93yvHn7/LeH73F8aO77HY7ELA9WXP8+l0UEhKBdLB894q9z+zTXNX4xtEsaoamp6lq8iJnt9ndHP43FUn495DAL66UYlzirKEoimh23FlUrlBSkuQZyTjaZ5ptTz4raK4qsnFBfbYlLwrcNFAkBYlKuDq5oKla3GCZ7E+5/PCCbtFw/OpdINBtOqSWCCWQQrA6W5GOMvoqDpTqTXWdPJGF5G1cIZh2IJvkmMH+xIflnY+iBTIOUJx3mN7EPeRmR5ZndG13k6hxip3iww+RD8RPLyVv4yeX4C9AHi+e9+xgj7aOhIr1fBUJBZUlyROGzkSBbMFN6QwwPZqRjjO2VxuUkPSbKAnkvOfu3bu0bYfSir7rSbKE9fkS6RX7D/c5f+8sujL2sTVq6hqkpCgKtlcb9h7us3m2IilT9l8/pL9s0FmC9AI5TQgm0K1amvkObx191dN3XTQENxapZWwRkuRTERd+DglMHBgYR5qmcflepPS7niRL6TZtlPuURB7mOMe0UWrVNjYCLYwnDA5jDBpFNs5vbBWLomDv/gHPvvcBSmq89RTjnPXFmtm9PZbPFyipGO9PWF+sEKmIp3CI5bJU4qbn9f56/+rCTx3QRbUMjXeeJEluSPjGGLIijzu76xv2hW72bdL+uxuCIYhDqms1j+5aakYpFYnztUNlGtMaIHyEbAsf9dqjwzFN0xCGgCoiYMdse0ajEcW4xPQDm8U22vRkCccPjwkC6nlFMcppNw2T4ynNpiLdy9k9W2Fag+8ch68f8/x7J+w93KdIc7pVy/h4wuZkdc048ygh6HYd3bpls9pgrbnZUHjnUVp9YtWNn2sCex9vrWIaF+gEKKej+EE6QzrOcb1jGAzOOUSAZlWTjjLScUqzqAjeR4tFPMvTBWmRRZHzEFhdLXn0uce02walo+RnCLB4PufR5x9z9eEFSZpEETelaavm42XbNek92MD4eIpph0/0Er0oqZ118ffeIxB4H4XpCB9B4IKP4JafmeJ3Gzff2Yt9vfPuphISQlCUBevlOu7wr29bQrieOn9UhgopyEY5CGi3ETTRrbqb2/nOgzvUuzqasFtHuTei20YFjCxPabYNxaS8+S/Nn10yO5xx9eEVUkomD6dcvX2Bt447n71HdbpjdDim33bsVluSNMEbR7NsaFd15Fz3/c2BJFQE8UgpP5Fs7M89gSNDJcphZkVO13a0VRu9i5zHu0A+LeiruGfTZYJpeuzg2J5tmN7fg0kcLNSbht0mEuPxHoTEO0e9rnnwxcesz5Z0Vcv0zpRm07CeRyZHXTWkaUK9rSMg40VZEqLH0IuEM80QZU1+2oMLPwI0CH91ihrNuMLHBmE/Onm+jZ+thE6zFGssxai4QaxVVfXxRH9ByfyRgb4SiunxlM1iQyI1pjOxdO4d5bi84WBv11vSLKNa7ShnY7yxFGXBZrnG9Rad6BvI7+nbzxlNSzbLDeVkxOp0yf79A3SZ0K5rhJLYdogWMj5Eu9OLNV0bk/dFxeavFSc/ycT+5zBeuI3buI2/bSFvH8Ft3MZtAt/GbdzGbQLfxm3cxm0C38Zt3CbwbdzGbdwm8G3cxm3cJvBt3MZt3CbwbdzGbQLfxm3cxm0C38Zt3MZtAt/Gbdwm8G3cxm3cJvBt3MZt3CbwbdzGbdwm8G3cxm0C38Zt3MZtAt/GbdzGbQLfxm3cxm0C38Zt3MZt3MZt/HuO/xezstUjEabBFQAAAABJRU5ErkJggg==';

// META includes
const fflate = require("fflate");
const msgHelper = require("WAWebMsgGetters");
const contactHelper = require("WAWebContactGetters");

const contactCollection = (require("WAWebContactCollection")).ContactCollection;
const chatCollection = (require("WAWebChatCollection")).ChatCollection;
const profilePicThumbCollection = (require("WAWebProfilePicThumbCollection")).ProfilePicThumbCollection;
const userAccountData = require("WAWebUserPrefsMeUser");

window.ZAPiX._zipFiles = {};

function addFile2Zip(fileName, payload) {
    window.ZAPiX._zipFiles[fileName] = payload;
}
// ------UTILS functions

var blobfy = function (obj){
	const str = JSON.stringify(obj);
	const bytes = new TextEncoder().encode(str);
	//const blob = new Blob([bytes], {    type: "application/json;charset=utf-8"});
	return bytes;

}

function htmlToPlainText(html) {
    const tempElement = document.createElement('div');
    tempElement.innerHTML = html;

    // Extract text content and alt attributes from <img> tags
    const imgTags = tempElement.querySelectorAll('img');
    imgTags.forEach((img) => {
        const altText = img.getAttribute('alt');
        if (altText) {
            img.insertAdjacentText('afterend', `${altText}`);
        }
    });

    return tempElement.textContent;
}

function base64ToArrayBuffer(base64) {
    var binary_string = window.atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}

function isElectron() {
    // Renderer process
    if (typeof window !== 'undefined' && typeof window.process === 'object' && window.process.type === 'renderer') {
        return true;
    }

    // Main process
    if (typeof process !== 'undefined' && typeof process.versions === 'object' && !!process.versions.electron) {
        return true;
    }

    // Detect the user agent when the `nodeIntegration` option is set to true
    if (typeof navigator === 'object' && typeof navigator.userAgent === 'string' && navigator.userAgent.indexOf('Electron') >= 0) {
        return true;
    }

    return false;
}


var b64toBlob = (b64Data, contentType='', sliceSize=512) => {
  const byteCharacters = atob(b64Data);
  const byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    const slice = byteCharacters.slice(offset, offset + sliceSize);

    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  const blob = new Blob(byteArrays, {type: contentType});
  return blob;
}

window.ZAPiX._serializeRawObj = (obj) => {
    if (obj && obj.toJSON) {
        return obj.toJSON();
    }
    return {}
};

/**
 * Serializes a chat object
 *
 * @param rawChat Chat object
 * @returns {{}}
 */

window.ZAPiX._serializeChatObj = (obj) => {
    if (obj == undefined) {
        return null;
    }
    return Object.assign(window.ZAPiX._serializeRawObj(obj), {
        id: obj.id._serialized,
        kind: obj.kind,
        isGroup: obj.isGroup,
        formattedTitle: obj.formattedTitle,
        contact: obj['contact'] ? window.ZAPiX._serializeContactObj(obj['contact']) : null,
        groupMetadata: obj["groupMetadata"] ? window.ZAPiX._serializeRawObj(obj["groupMetadata"]) : null,
        presence: obj["presence"] ? window.ZAPiX._serializeRawObj(obj["presence"]) : null,
        msgs: null
    });
};

window.ZAPiX._serializeContactObj = (obj) => {
    if (obj == undefined) {
        return null;
    }
    return Object.assign(window.ZAPiX._serializeRawObj(obj), {
        id: obj.id._serialized,
        formattedName: obj.formattedName,
        isHighLevelVerified: obj.isHighLevelVerified,
        isMe: obj.isMe,
        isMyContact: obj.isMyContact,
        isPSA: obj.isPSA,
        isUser: obj.isUser,
        isVerified: obj.isVerified,
        isWAContact: obj.isWAContact,
        profilePicThumbObj: obj.profilePicThumb ? ZAPiX._serializeProfilePicThumb(obj.profilePicThumb) : {},
        statusMute: obj.statusMute,
        msgs: null
    });
};


window.ZAPiX._serializeMessageObj = (obj) => {
    if (obj == undefined) {
        return null;
    }
    const _chat = obj['chat'] ? ZAPiX._serializeChatObj(obj['chat']) : {};
    if (obj.quotedMsg) obj.quotedMsgObj;
    return Object.assign(window.ZAPiX._serializeRawObj(obj), {
        id: obj.id._serialized,
        from: obj.from._serialized,
        quotedParticipant: obj.quotedParticipant ? obj.quotedParticipant._serialized ? obj.quotedParticipant._serialized : undefined : undefined,
        author: obj.author ? obj.author._serialized ? obj.author._serialized : undefined : undefined,
        chatId: obj.chatId ? obj.chatId._serialized ? obj.chatId._serialized : undefined : undefined,
        to: obj.to ? obj.to._serialized ? obj.to._serialized : undefined : undefined,
        fromMe: obj.id.fromMe,
        sender: obj["senderObj"] ? ZAPiX._serializeContactObj(obj["senderObj"]) : null,
        timestamp: obj["t"],
        content: obj["body"],
        isGroupMsg: obj.isGroupMsg,
        isLink: obj.isLink,
        isMMS: obj.isMMS,
        isMedia: obj.isMedia,
        isNotification: obj.isNotification,
        isPSA: obj.isPSA,
        type: obj.type,
        chat: _chat,
        isOnline: _chat.isOnline,
        lastSeen: _chat.lastSeen,
        chatId: obj.id.remote,
        quotedMsgObj: window.ZAPiX._serializeMessageObj(obj['_quotedMsgObj']),
        mediaData: window.ZAPiX._serializeRawObj(obj['mediaData']),
        reply: body => window.ZAPiX.reply(_chat.id._serialized, body, obj)
    });
};

window.ZAPiX._serializeNumberStatusObj = (obj) => {
    if (obj == undefined) {
        return null;
    }

    return Object.assign({}, {
        id: obj.jid,
        status: obj.status,
        isBusiness: (obj.biz === true),
        canReceiveMessage: (obj.status === 200)
    });
};

window.ZAPiX._serializeProfilePicThumb = (obj) => {
    if (obj == undefined) {
        return null;
    }

    return Object.assign({}, {
        eurl: obj.eurl,
        id: obj.id,
        img: obj.img,
        imgFull: obj.imgFull,
        raw: obj.raw,
        tag: obj.tag
    });
}


// Main tasks functions
window.ZAPiX._getUser = function (){
	return (userAccountData.getMaybeMeDevicePn()._serialized).replaceAll('\"','').replaceAll(":","_"); 
	//return (localStorage.getItem("last-wid-md")).replaceAll('\"','').replaceAll(":","_");
}

window.ZAPiX._downloadFile2Array = async function (url) {
    if (!url) return false;
    //console.log(url);
    const response = await fetch(url);
    const ab = await response.arrayBuffer();
    return btoa(new Uint8Array(ab).reduce((data, byte) => data + String.fromCharCode(byte), ''));
};


window.ZAPiX._getProfilesPics = async function(contacts){
    for(var i = 0; i < contacts.length; i++) {
		var obj = contacts[i];
		window.ZAPiX._statusTextnode.data = "ProfilePic "+obj.id+"-"+i+"/"+contacts.length;
		console.log("Reading data id: "+obj.id);
        picArray = profilePicThumbCollection._models.filter((p)=>p.__x_id._serialized === obj.id);
        if (picArray.length > 0){
            //console.log('URL:');
            url = picArray[0].__x_imgFull;
            //console.log(url);
            if (typeof url !== 'undefined' && url !== null) {
                try{
                    const response = await fetch(url);
                    const data = await response.arrayBuffer();
                    addFile2Zip("Avatar "+obj.id+".jpg", [new Uint8Array(data),{ level:0}]);
                    console.log("Avatar "+obj.id+" saved");
                } catch (error) {
                    console.error("Avatar "+obj.id+" NOT saved - ", error);
                }
            }
        }
		
	}
}

window.ZAPiX._downloadMediaFile = async function(msg) {
    
	console.log("Download media file");
	//console.log(msg);
    
    var url = msgHelper.getDeprecatedMms3Url(msg);
	var dec_media_withpad = base64ToArrayBuffer(await window.ZAPiX._downloadFile2Array(url));
	//console.log(dec_media_withpad);
	var dec_media = dec_media_withpad.slice(0,dec_media_withpad.byteLength-10);
	//console.log(dec_media);
    var mediaType = msgHelper.getType(msg);
	window.ZAPiX._mediaTypes.add(mediaType);
	var mediakey = msgHelper.getMediaKey(msg);
	console.log(window.ZAPiX._decodeZapMedia[mediaType]);
    var mediaKeyExpanded = 'notExpanded'
    mediaHkdf = require("WACryptoHkdf");
	//console.log(mediakey);
    var mediaKeyExpanded = await mediaHkdf.extractAndExpand(base64ToArrayBuffer(mediakey), window.ZAPiX._decodeZapMedia[mediaType], 112);
    //mediaKeyExpanded.then((data)=> expandedKey = data);
    //console.log(mediaKeyExpanded);
	var ivd = new Uint8Array(mediaKeyExpanded.slice(0, 16));
	//console.log('IV:'+ivd+" bytelength:"+ivd.byteLength);
    var cipherKey = new Uint8Array(mediaKeyExpanded.slice(16,48));
	//console.log('CypherKey:'+cipherKey+" bytelength:"+cipherKey.byteLength);
	var decAESkey = await crypto.subtle.importKey('raw',cipherKey,{ name: 'AES-CBC' },false, ['decrypt']);
	//console.log('decAESKey:');
    //console.log(decAESkey);
    var decoded = await crypto.subtle.decrypt({name:'AES-CBC', iv:new Uint8Array(ivd)}, decAESkey, dec_media);
	//console.log('decrypted:');
	//console.log(decoded);
	if (decoded.byteLength == 0)
	{
		console.log('Media file NOT decrypted');
	} else {
        console.log('Saving:','Attachment '+msgHelper.getId(msg)+window.ZAPiX._fileExtensions[msgHelper.getMimetype(msg)]);
		addFile2Zip('Attachment '+msgHelper.getId(msg)+window.ZAPiX._fileExtensions[msgHelper.getMimetype(msg)], [new Uint8Array(decoded),{ level:0}]);  
		console.log('Media file decrypted');
	}
};

window.ZAPiX._getUserContacts =  function () {
    return contactCollection._models.filter((contact) => contactHelper.getIsMyContact(contact) === true || contactHelper.getIsMe(contact) === true).map((contact) => window.ZAPiX._serializeContactObj(contact));
};

window.ZAPiX._getAllChats = function () {
    return chatCollection._models.map((chat) => window.ZAPiX._serializeChatObj(chat));
};

window.ZAPiX._internal_start = async function(){
	window.ZAPiX._statusTextnode.data = "Extracting User Account...";
	var userAccount = contactCollection.getMeContact(); //await userAccountData.getMe();
	window.ZAPiX._statusTextnode.data = "Extracting User Contacts...";
	var contacts = await window.ZAPiX._getUserContacts();
	window.ZAPiX._statusTextnode.data = "Saving User Account...";
    addFile2Zip("userAccount.json", [blobfy(userAccount),{ level:9}]); 
	console.log('User account - Ok');
	window.ZAPiX._statusTextnode.data = "Saving User Contacts...";
    addFile2Zip("contacts.json", [blobfy(contacts), {level:9}]);

    console.log('User contacts - Ok');
	window.ZAPiX._statusTextnode.data = "Extracting User (recent) Chats...";
	var chats = await window.ZAPiX._getAllChats();
	window.ZAPiX._statusTextnode.data = "Saving User Chats...";
    addFile2Zip("chats.json", [blobfy(chats),{level:9}]);
    
    console.log('User chats - Ok');
	window.ZAPiX._statusTextnode.data = "Extracting Profile Pics...";
	console.log('Download Profiles Pics');
	try{
		await window.ZAPiX._getProfilesPics(contacts);
	}
	catch(e){
		console.log('Error extracting profilePics');
	}
	window.ZAPiX._statusTextnode.data = "Account, Contact and ProfilePic data collected";
}

window.ZAPiX._internal_saveAttachmentPreview = function(msg){
	try{
		var blob;
        console.log(msg);
        if (msgHelper.getBody(msg)!=''){
            console.log(msgHelper.getBody(msg))
            console.log('call b64toBlob')
            blob = b64toBlob(msgHelper.getBody(msg));
            console.log('end call b64toBlob')
        }
		var mimetypeFileExtension = window.ZAPiX._fileExtensions[msgHelper.getMimetype(msg)];
		if (msg['type']=='vcard'){
			mimetypeFileExtension = window.ZAPiX._fileExtensions['text/x-vcard'];
		}else{
			//blob = msgHelper.getMediadatamsg['mediaData']['fullPreviewData']['_blob'];
			mimetypeFileExtension = window.ZAPiX._fileExtensions[msg['mimetype']]+window.ZAPiX._fileExtensions[msg['mediaData']['fullPreviewData']['_mimetype']];
		}
		//window.ZAPiX._zip.addFile(blob, {filename: stringToByteArray('Attachment '+msg['id']+'.embedded'+mimetypeFileExtension)});
		console.log('Attachment '+msg['id']+'.embedded'+mimetypeFileExtension);
        addFile2Zip('Attachment '+msg['id']+'.embedded'+mimetypeFileExtension, blob);
		console.log("Saved ");
	}catch(e){
		console.log("NOT saved - "+e.message);
	}
}

window.ZAPiX._internal_getallchats = async function (){
    var chats = chatCollection._models;
	var chatCount = chats.length;
	window.ZAPiX._statusTextnode.data = "Extracting User Chat Messages and attachments...";
	console.log('Getting messages from:'+chatCount+' chats');
	for (var i = 0; i < chatCount; i++) {
		chatName = chats[i].__x_formattedTitle;
		var msgs = chats[i].msgs._models;
		addFile2Zip('Chat '+chats[i].__x_id+'.json', [blobfy(msgs),{ level:9}]);
        chatName = chats[i].__x_formattedTitle; 
		for (var m=0; m < msgs.length; m++){
			window.ZAPiX._statusTextnode.data = "Chat "+chatName+"-"+i+"/"+chatCount+" - Message "+m+"/"+msgs.length;
		
			msgType = msgHelper.getType(msgs[m]);
			if (msgType=='image' || msgType=='video' || msgType=='ptt' || msgType=='document' || msgType=='sticker'){
				try{
					await window.ZAPiX._downloadMediaFile(msgs[m]);
				}catch(e){
					console.log('Error downloading '+msgType+':'+e.message+". Using embedded data.");
					//window.ZAPiX._internal_saveAttachmentPreview(msgs[m])
				}
			} 
			else if (msgType=='vcard'){
				try{
					mimetypeFileExtension = window.ZAPiX._fileExtensions['text/x-vcard'];
					addFile2Zip('Attachment '+msgHelper.getId(msgs[m])+'.embedded'+mimetypeFileExtension, [fflate.strToU8(msgHelper.getBody(msgs[m])),{ level:9}]);
					console.log("Vcard Saved ");
				}catch(e){
					console.log("Vcard NOT saved - "+e.message);
				}
			}
		}
		window.ZAPiX._statusTextnode.data = "Chat "+chatName+" extracted";
	}
	window.ZAPiX._statusTextnode.data = chatCount+" chats extracted";
}
	
window.ZAPiX._decodeHtmlEntities = function(str) {
    return str.replace(/&amp;/g, '&')
              .replace(/&lt;/g, '<')
              .replace(/&gt;/g, '>')
              .replace(/&quot;/g, '"')
              .replace(/&#39;/g, "'");
}

window.ZAPiX._internal_getChatByName = function(chatName){
	ret = null
	chatName = window.ZAPiX._decodeHtmlEntities(chatName).trimStart().trimEnd();
	chatName = window.htmlToPlainText(chatName)
	var chats = window.ZAPiX._getAllChats();
	for (var i = 0; i < chats.length; i++) {
		//console.log(chats[i].formattedTitle);
		if ((chats[i].isGroup && chats[i].name == chatName)||(!chats[i].isGroup && chats[i].formattedTitle == chatName)||(!chats[i].isGroup && chats[i].contact.name == chatName)){
			console.log("Found:"+chats[i].name)
			ret =  chats[i]
			break;
		}
	}
	return ret;
}

window.ZAPiX._internal_getchat = async function (chatName){
	window.ZAPiX._statusTextnode.data = "Extracting User Chat "+chatName+" messages and attachments...";
	console.log('Getting messages from:'+chatName+' chats');
	chat = window.ZAPiX._internal_getChatByName(chatName);
	if (chat == null){
		console.log('Chat:'+chatName+' not found.');
		window.ZAPiX._statusTextnode.data = 'Chat:'+chatName+' not found.';
		return;
	}
	console.log('Getting messages from:'+chat.id+' chats');
    resultOfFiltering = chatCollection._models.filter((c)=>c.__x_id._serialized === chat.id)
    if (resultOfFiltering.length > 0){
        var msgs = resultOfFiltering[0].msgs._models;
        //console.log(msgs);
        addFile2Zip('Chat '+chat.id+'.json', [blobfy(msgs),{ level:9}]); 
		for (var m=0; m < msgs.length; m++){
            msgType = msgHelper.getType(msgs[m]);
            console.log(msgType);
			if (msgType=='image' || msgType=='video' || msgType=='ptt' || msgType=='document' || msgType=='sticker'){
				try{
					await window.ZAPiX._downloadMediaFile(msgs[m]);
				}catch(e){
					console.log('Error downloading '+msgType+':'+e.message+". Using embedded data.");
					//window.ZAPiX._internal_saveAttachmentPreview(msgs[m])
				}
			} 
			else if (msgType=='vcard'){
				try{
					mimetypeFileExtension = window.ZAPiX._fileExtensions['text/x-vcard'];
					addFile2Zip('Attachment '+msgHelper.getId(msgs[m])+'.embedded'+mimetypeFileExtension, [fflate.strToU8(msgHelper.getBody(msgs[m])),{ level:9}]);
					console.log("Vcard Saved ");
				}catch(e){
					console.log("Vcard NOT saved - "+e.message);
				}
			}
		}
    	window.ZAPiX._statusTextnode.data = chatName+" extracted!";
    }
}
async function saveFile(dataFile, fileName) {
	if (!(dataFile instanceof Blob)){
		dataFile = new Blob([dataFile], {type:'text/plain'});
	}
	const opts = {
	suggestedName: fileName
	};
	const blobURL = URL.createObjectURL(dataFile);
    const link = document.createElement("a");
    link.href = blobURL;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(blobURL);
	
	/*const newHandle = await window.showSaveFilePicker(opts);
	const options = {};
	options.mode = 'readwrite';
	await newHandle.requestPermission(options);
	const writableStream = await newHandle.createWritable();
	await writableStream.write(dataFile);
	await writableStream.close();*/
}


window.ZAPiX.showDigest = function(){
	var hashHex = window.ZAPiX._lastDigest;
	if (hashHex!=undefined){
		var userAccount = window.ZAPiX._getUser();
		var content = hashHex +" ?SHA512*"+ "ZAPiXWEB_"+userAccount+".zip";
		saveFile(content, "ZAPiXWEB_"+userAccount+".sha512.txt");
		//var hashFile = new File([(content)],userAccount+".sha512.txt", {type: "text/plain;charset=utf-8"});
		/*if (isElectron()){
			saveAsElectron(content, "hash");
		} else {
			saveFile(userAccount+".sha512.txt", content);
		}*/
	}

}

window.ZAPiX._internal_end = async function (){
	var userAccount = window.ZAPiX._getUser();
    var fileName = "ZAPiXWEB_"+userAccount+".zip";
    var zip = await fflate.zipSync(window.ZAPiX._zipFiles);
    var blobzip = new Blob([zip], { type: 'application/zip' });
    await saveFile(blobzip,fileName);
	window.ZAPiX._statusTextnode.data = "Extracted data saved.";
	window.ZAPiX._statusTextnode.data = "Calculating hash";
	const hashBuffer = await crypto.subtle.digest('SHA-512',new Uint8Array(zip));
	const hashArray = Array.from(new Uint8Array(hashBuffer));
	// convert buffer to byte array
	window.ZAPiX._lastDigest = hashArray.map(b => b.toString(16).padStart(2, '0')).join(''); 
	if (!isElectron())
		window.ZAPiX.showDigest();
	
	window.ZAPiX._statusTextnode.data = "Extracted data saved.";
}

window.ZAPiX._clearUI = function (){
	var uiElements = document.getElementById('zapixweb_header_div');
	while (uiElements!=null){
		uiElements.remove();
		uiElements = document.getElementById('zapixweb_header_div');
	}
}

window.ZAPiX._bootstrap = function(){
	// BOOTSTRAP
	console.clear();
	window.ZAPiX._clearUI();
	console.log(window.ZAPiX._zapix_header);
	console.log('Please wait.Save the file after extraction.');
	var zapixweb_html = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|_|_|&nbsp;&nbsp;&nbsp;_|_|_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_|_|	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|&nbsp;&nbsp;_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|_|&nbsp;&nbsp;&nbsp;&nbsp;_|_|_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|&nbsp;&nbsp;&nbsp;_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|	<br>&nbsp;&nbsp;&nbsp;&nbsp;_|_|_|&nbsp;&nbsp;&nbsp;_|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_|_|_|	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ZAPiX Web<br>W&nbsp;H&nbsp;A&nbsp;T&nbsp;S&nbsp;A&nbsp;P&nbsp;P&nbsp;W&nbsp;E&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;E&nbsp;X&nbsp;T&nbsp;R&nbsp;A&nbsp;C&nbsp;T&nbsp;O&nbsp;R<br><br>';
	zapixweb_html += '<div id="zapixweb_status">Starting...</div>';
	alert('     _|_|_|   _|_|_|     |_|_|	\n    _|        _|  _|       _|	\n      _|_|    _|_|_|       _|	\n         _|   _|           _|	\n    _|_|_|    _|         _|_|_|	\n	                      ZAPiX Web\nW H A T S A P P W E B  E X T R A C T O R\n Follow the instruction in console window.');
	
	window.ZAPiX._injectedHeaderNode = document.createElement("DIV");
	window.ZAPiX._injectedHeaderNode.id = 'zapixweb_header_div'
	window.ZAPiX._injectedHeaderNode.setAttribute('align','middle');
	window.ZAPiX._injectedHeaderNode.innerHTML = '<img src="data:image/png;base64,'+window.ZAPiX._logo+'" alt="ZAPIXWEB LOGO" />'
	//var headerTextnode = document.createTextNode('Z A P i X W E B');
	//headerTextnode.id = 'zapixweb_header'
	//window.ZAPiX._injectedHeaderNode.appendChild(headerTextnode); 
	document.getElementById("pane-side").previousSibling.appendChild(window.ZAPiX._injectedHeaderNode);
	

	window.ZAPiX._mainMenu = document.createElement("DIV");
	window.ZAPiX._mainMenu.setAttribute("class","app-wrapper-web");
	window.ZAPiX._mainMenu.setAttribute('align','middle');
	window.ZAPiX._mainMenu.id = 'zapixweb_menu_div'
	
	//var style = document.createElement('style');
	//style.innerHTML = '{border: none;padding: 7px 26px;text-align: center;color: white;background: #dc3545;border-radius: 40px;}';
	var s = 'width: 100%;border: 1px solid black;padding: 1px 26px;text-align: left;color: white;background: forestgreen;border-radius: 40px;';
	var s2 = 'width: 100%;border: 1px solid black;padding: 1px 26px;text-align: left;color: white;background: darkgreen;border-radius: 40px;';
	//document.head.appendChild(style);
	window.ZAPiX._mainMenu.innerHTML = "MENU</br> <button id='zapixGetCurrentChatButton' title='Add the current selected chat in export list.' style='"+s+"'>ADD CURRENT CHAT</button></br><button  title='Add ALL chats into the export list.' id='zapixGetAllChatsButton' style='"+s+"'>GET ALL CHATS</button></br><button id='zapixTakeoutButton' title='Pack all data into ZIP file.' style='"+s+"'>TAKEOUT</button></br><button id='zapixShowDigestButton' title='Show the last calculated digest' style='"+s+"'>LAST DIGEST</button></br><button id='zapixCloseButton' title='Exit ZAPiXWEB' style='"+s2+"'>CLOSE</button></br>"
	//window.ZAPiX.getchat(this)
    window.ZAPiX._mainMenu.getElementsByTagName("button").namedItem("zapixGetCurrentChatButton").addEventListener("click", function(){window.ZAPiX.getchat(this)});
    window.ZAPiX._mainMenu.getElementsByTagName("button").namedItem("zapixGetAllChatsButton").addEventListener("click", function(){window.ZAPiX.getall(this)});
    window.ZAPiX._mainMenu.getElementsByTagName("button").namedItem("zapixTakeoutButton").addEventListener("click", function(){window.ZAPiX.takeout(this)});
    window.ZAPiX._mainMenu.getElementsByTagName("button").namedItem("zapixShowDigestButton").addEventListener("click", function(){window.ZAPiX.showDigest(this)});
    window.ZAPiX._mainMenu.getElementsByTagName("button").namedItem("zapixCloseButton").addEventListener("click", function(){window.ZAPiX.closeUI(this)});
    
    window.ZAPiX._injectedHeaderNode.appendChild(window.ZAPiX._mainMenu);
	
	window.ZAPiX._injectedStatusNode = document.createElement("DIV");
	window.ZAPiX._injectedStatusNode.id = 'zapixweb_status_div'
	window.ZAPiX._injectedStatusNode.setAttribute('align','middle');
	window.ZAPiX._injectedStatusNode.setAttribute('style','font-size:12px; border: 1px solid green');

	window.ZAPiX._statusTextnode = document.createTextNode('Starting...');
	window.ZAPiX._statusTextnode.id = 'zapixweb_status';
	window.ZAPiX._injectedStatusNode.appendChild(window.ZAPiX._statusTextnode); 
	//document.getElementById("pane-side").previousSibling.appendChild(window.ZAPiX._injectedStatusNode);
	window.ZAPiX._injectedHeaderNode.appendChild(window.ZAPiX._injectedStatusNode);
	
	window.ZAPiX._internal_start()
	
	console.log(window.ZAPiX._zapix_header);
	//console.log('To extract all chats, click GETALL');
	//console.log('To extract specific chat, open the chat windows , and click GETCHAT');
	//console.log('You can repeate this last command selecting another chat windows. You can extract as many chats as you want');

	window.ZAPiX._statusTextnode.data = "ZAPiX choose type your operation in menu";
}

window.ZAPiX.getall = function (btn){
	btn.style.background = 'darkgreen';
	window.ZAPiX._internal_getallchats();
	btn.style.background = 'forestgreen';
	window.ZAPiX._statusTextnode.data = "All User Chat Messages and attachments extracted";
	console.log(window.ZAPiX._zapix_header);
	console.log(window.ZAPiX._statusTextnode.data);
}

window.ZAPiX.getchat = function (btn){
	if (document.getElementById("main") == null){
		alert('     _|_|_|   _|_|_|     |_|_|	\n    _|        _|  _|       _|	\n      _|_|    _|_|_|       _|	\n         _|   _|           _|	\n    _|_|_|    _|         _|_|_|	\n	                      ZAPiX Web\nW H A T S A P P W E B  E X T R A C T O R\n Before execute command, select a chat do extract data. Open chat clicking the mouse over it.');
		
		console.log('Before execute command, select a chat do extract data. Open chat clicking the mouse over it.');
		return;
	}
	btn.style.background = 'darkgreen';
	spanIndex = 0;
	var chatTitle = document.getElementById("main").getElementsByTagName('span')[spanIndex];
	while (chatTitle.dir != 'auto'){
		chatTitle = document.getElementById("main").getElementsByTagName('span')[++spanIndex];
	}
	console.log(document.getElementById("main").getElementsByTagName('span')[spanIndex].title)
	chatName=document.getElementById("main").getElementsByTagName('span')[spanIndex].title;
	
	if (chatName=='' ){
		chatName=document.getElementById("main").getElementsByTagName('span')[spanIndex].innerHTML
	}
	//window.ZAPiX._internal_getchat(document.getElementById("main").getElementsByTagName('span')[spanIndex].title)
	window.ZAPiX._internal_getchat(chatName)
	btn.style.background = 'forestgreen';

	console.log(window.ZAPiX._zapix_header);
	console.log('To extract specific chat, open the chat windows , and click GET CURRENT CHAT');
	console.log('You can repeate this last command selecting another chat windows. You can extract as many chats as you want');
	console.log('To FINISH click TAKEOUT');
}

window.ZAPiX.takeout = function (btn){
	console.clear();
	console.log(window.ZAPiX._zapix_header);
	console.log('Generating export file. Wait the file dialog. It can take several minutes.');
	window.ZAPiX._statusTextnode.data = "Packing takeout.. (Please wait save file dialog) - Save It.";
	console.log('After file saved, wait for HASH digest!!!!!!. Wait.');
	btn.style.background = 'darkgreen';
	window.ZAPiX._internal_end();
	btn.style.background = 'forestgreen';
	window.ZAPiX._clearUI();
	console.clear();
	console.log(window.ZAPiX._zapix_header);
	console.log('A ZIP file and a SHA512 hash are beeing generated. It can take several minutes.');
	console.log('WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!WAIT!');
	console.log('Have a nice forensics!');
}
window.ZAPiX.closeUI = function (btn){
	if (confirm('Z A P i X W E B \n Do you really want to exit?')){
		console.clear();
		btn.style.background = 'darkgreen';
		window.ZAPiX._clearUI();
		btn.style.background = 'forestgreen';
		console.log('Close this console window (most browsers hit F12)');
		console.clear();
	}
}

window.ZAPiX._bootstrap();

//PRESS ENTER KEY NOW TO EXECUTE THIS SCRIPT!!!!!

